//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllAllocations
    {
        public System.Guid AllocationID { get; set; }
        public decimal CompanyCode { get; set; }
        public string AllocationNumber { get; set; }
        public string AllocationRuleCode { get; set; }
        public bool IncludeWarehouseInventory { get; set; }
        public bool IncludeRemainingOrder { get; set; }
        public bool IncludeRemainingOrderAsn { get; set; }
        public string SourceApplicationCode { get; set; }
        public Nullable<System.Guid> SourceApplicationID { get; set; }
        public string WarehouseCode { get; set; }
        public System.DateTime OperationDate { get; set; }
        public string Description { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsLocked { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsConfirmed { get; set; }
        public bool IsCalculated { get; set; }
        public string ConfirmedUserName { get; set; }
        public System.DateTime ConfirmedDate { get; set; }
        public byte UseRemainingOrderOption { get; set; }
        public bool IsPostingOrder { get; set; }
        public bool IsPostingStoreOrder { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public System.Guid SubCurrAccID { get; set; }
        public int SortOrder { get; set; }
        public string StoreCode { get; set; }
        public string CustomerCode { get; set; }
        public string ProductTypeCode { get; set; }
        public string ProductCode { get; set; }
        public string ColorCode { get; set; }
        public string ItemDim1Code { get; set; }
        public string ItemDim2Code { get; set; }
        public string ItemDim3Code { get; set; }
        public System.Guid OrderLineID { get; set; }
        public System.Guid OrderAsnLineID { get; set; }
        public double AllocationQty1 { get; set; }
        public double Qty1 { get; set; }
        public string LotCode { get; set; }
        public int LotQty { get; set; }
        public System.Guid AllocationProductQtyID { get; set; }
        public System.Guid AllocationChannelID { get; set; }
        public System.Guid AllocationProductID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
