//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllBanks
    {
        public System.Guid BankHeaderID { get; set; }
        public byte BankTransTypeCode { get; set; }
        public string BankTransNumber { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public System.TimeSpan DocumentTime { get; set; }
        public string DocumentNumber { get; set; }
        public string RefNumber { get; set; }
        public string Description { get; set; }
        public string OfficeCode { get; set; }
        public byte StoreTypeCode { get; set; }
        public string StoreCode { get; set; }
        public short POSTerminalID { get; set; }
        public double ExchangeRate { get; set; }
        public bool SetDocumentTypeAsJournal { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsLocked { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsPostingJournal { get; set; }
        public System.DateTime JournalDate { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid BankLineID { get; set; }
        public int SortOrder { get; set; }
        public byte BankCurrAccTypeCode { get; set; }
        public string BankCurrAccCode { get; set; }
        public bool IsBankDebited { get; set; }
        public Nullable<byte> CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public Nullable<System.Guid> SubCurrAccID { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public System.DateTime DueDate { get; set; }
        public string LineDescription { get; set; }
        public string BankReferenceNumber { get; set; }
        public string BankConfirmationNumber { get; set; }
        public float TaxRate { get; set; }
        public byte EmployeePayTypeCode { get; set; }
        public double Qty { get; set; }
        public byte BankOpTypeCode { get; set; }
        public decimal CompanyCode { get; set; }
        public string GLAccCode { get; set; }
        public string CostCenterCode { get; set; }
        public string GLTypeCode { get; set; }
        public byte DocumentTypeCode { get; set; }
        public string DocumentTypeDescription { get; set; }
        public string PaymentMethod { get; set; }
        public string ImportFileNumber { get; set; }
        public string ExportFileNumber { get; set; }
        public string RelatedBankCode { get; set; }
        public string RelatedBankBranchCode { get; set; }
        public string RelatedBankAccNo { get; set; }
        public string RelatedIBAN { get; set; }
        public bool IsTransferChargeIncluded { get; set; }
        public string DocCurrencyCode { get; set; }
        public string CurrAccCurrencyCode { get; set; }
        public double CurrAccExchangeRate { get; set; }
        public decimal CurrAccAmount { get; set; }
        public Nullable<System.Guid> BankPaymentInstructionLineID { get; set; }
        public Nullable<System.Guid> BankCreditLineID { get; set; }
        public string RelatedCurrAccDescription { get; set; }
        public string ProvisionNumber { get; set; }
        public string Doc_CurrencyCode { get; set; }
        public decimal Doc_Amount { get; set; }
        public decimal Doc_TransferCharges { get; set; }
        public decimal Doc_StampTax { get; set; }
        public decimal Doc_Tax { get; set; }
        public decimal Doc_TaxAmount { get; set; }
        public decimal Doc_TaxAssessment { get; set; }
        public string Loc_CurrencyCode { get; set; }
        public double Loc_ExchangeRate { get; set; }
        public decimal Loc_Amount { get; set; }
        public decimal Loc_TransferCharges { get; set; }
        public decimal Loc_StampTax { get; set; }
        public decimal Loc_Tax { get; set; }
        public decimal Loc_TaxAmount { get; set; }
        public decimal Loc_TaxAssessment { get; set; }
        public string Com_CurrencyCode { get; set; }
        public double Com_ExchangeRate { get; set; }
        public decimal Com_Amount { get; set; }
        public decimal Com_TransferCharges { get; set; }
        public decimal Com_StampTax { get; set; }
        public decimal Com_Tax { get; set; }
        public decimal Com_TaxAmount { get; set; }
        public decimal Com_TaxAssessment { get; set; }
    }
}
