//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllInnerOrderLinesWithITAttributes
    {
        public System.Guid InnerOrderHeaderID { get; set; }
        public byte InnerOrderTypeCode { get; set; }
        public string InnerProcessCode { get; set; }
        public string InnerOrderNumber { get; set; }
        public System.DateTime InnerOrderDate { get; set; }
        public System.TimeSpan InnerOrderTime { get; set; }
        public string Description { get; set; }
        public string InternalDescription { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public Nullable<System.Guid> SubCurrAccID { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public decimal CompanyCode { get; set; }
        public string OfficeCode { get; set; }
        public byte StoreTypeCode { get; set; }
        public string StoreCode { get; set; }
        public string WarehouseCode { get; set; }
        public double SurplusOrderQtyToleranceRate { get; set; }
        public string ImportFileNumber { get; set; }
        public string ExportFileNumber { get; set; }
        public string ShipmentMethodCode { get; set; }
        public string RoundsmanCode { get; set; }
        public string DeliveryCompanyCode { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsLocked { get; set; }
        public bool UserLocked { get; set; }
        public bool IsPrinted { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public bool IsSectionTransfer { get; set; }
        public System.Guid InnerOrderLineID { get; set; }
        public int SortOrder { get; set; }
        public byte ItemTypeCode { get; set; }
        public string ItemCode { get; set; }
        public string ColorCode { get; set; }
        public string ItemDim1Code { get; set; }
        public string ItemDim2Code { get; set; }
        public string ItemDim3Code { get; set; }
        public double Qty1 { get; set; }
        public double Qty2 { get; set; }
        public double CancelQty1 { get; set; }
        public double CancelQty2 { get; set; }
        public System.DateTime CancelDate { get; set; }
        public string OrderCancelReasonCode { get; set; }
        public System.DateTime ClosedDate { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string LineDescription { get; set; }
        public string UsedBarcode { get; set; }
        public string PriceCurrencyCode { get; set; }
        public decimal Price { get; set; }
        public string BaseProcessCode { get; set; }
        public string BaseOrderNumber { get; set; }
        public int BaseCustomerTypeCode { get; set; }
        public string BaseCustomerCode { get; set; }
        public string BaseStoreCode { get; set; }
        public double LineSurplusOrderQtyToleranceRate { get; set; }
        public int InnerOrderLineSumID { get; set; }
        public string SectionCode { get; set; }
        public string ToSectionCode { get; set; }
        public Nullable<System.Guid> BaseCustomerOrderLineID { get; set; }
        public string ITAtt01 { get; set; }
        public string ITAtt02 { get; set; }
        public string ITAtt03 { get; set; }
        public string ITAtt04 { get; set; }
        public string ITAtt05 { get; set; }
        public string ITAtt06 { get; set; }
        public string ITAtt07 { get; set; }
        public string ITAtt08 { get; set; }
        public string ITAtt09 { get; set; }
        public string ITAtt10 { get; set; }
    }
}
