//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllIncentiveLines
    {
        public System.Guid IncentiveHeaderID { get; set; }
        public string IncentiveNumber { get; set; }
        public System.DateTime OperationDate { get; set; }
        public System.TimeSpan OperationTime { get; set; }
        public decimal CompanyCode { get; set; }
        public string WorkPlaceCode { get; set; }
        public short ValidYear { get; set; }
        public byte ValidMonth { get; set; }
        public string IncentiveTypeCode { get; set; }
        public string LocalCurrencyCode { get; set; }
        public double ExchangeRate { get; set; }
        public string Description { get; set; }
        public bool IsGrossEarnings { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsConfirmed { get; set; }
        public string ConfirmedUserName { get; set; }
        public System.DateTime ConfirmedDate { get; set; }
        public bool IsLocked { get; set; }
        public bool IsPostingPayroll { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid IncentiveLineID { get; set; }
        public int SortOrder { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public string LineDescription { get; set; }
        public string DocCurrencyCode { get; set; }
        public decimal IncentiveAmount { get; set; }
    }
}
