//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllStockWithITAttributes
    {
        public System.Guid StockID { get; set; }
        public byte TransTypeCode { get; set; }
        public string ProcessCode { get; set; }
        public string InnerProcessCode { get; set; }
        public bool IsReturn { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public System.TimeSpan DocumentTime { get; set; }
        public string DocumentNumber { get; set; }
        public System.DateTime OperationDate { get; set; }
        public System.TimeSpan OperationTime { get; set; }
        public byte ItemTypeCode { get; set; }
        public string ItemCode { get; set; }
        public string ColorCode { get; set; }
        public string ItemDim1Code { get; set; }
        public string ItemDim2Code { get; set; }
        public string ItemDim3Code { get; set; }
        public string BatchCode { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public Nullable<System.Guid> SubCurrAccID { get; set; }
        public decimal CompanyCode { get; set; }
        public string OfficeCode { get; set; }
        public byte StoreTypeCode { get; set; }
        public string StoreCode { get; set; }
        public string WarehouseCode { get; set; }
        public double In_Qty1 { get; set; }
        public double In_Qty2 { get; set; }
        public double Out_Qty1 { get; set; }
        public double Out_Qty2 { get; set; }
        public string FromOfficeCode { get; set; }
        public byte FromStoreTypeCode { get; set; }
        public string FromStoreCode { get; set; }
        public string FromWarehouseCode { get; set; }
        public string LineDescription { get; set; }
        public string LocalCurrencyCode { get; set; }
        public string DocCurrencyCode { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string SectionCode { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string ITAtt01 { get; set; }
        public string ITAtt02 { get; set; }
        public string ITAtt03 { get; set; }
        public string ITAtt04 { get; set; }
        public string ITAtt05 { get; set; }
        public string ITAtt06 { get; set; }
        public string ITAtt07 { get; set; }
        public string ITAtt08 { get; set; }
        public string ITAtt09 { get; set; }
        public string ITAtt10 { get; set; }
    }
}
