//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auAngolaSVCIntegrationInfo
    {
        public System.Guid AngolaSVCIntegrationInfoID { get; set; }
        public decimal CompanyCode { get; set; }
        public string OfficeCode { get; set; }
        public string StoreCode { get; set; }
        public string ApplicationName { get; set; }
        public System.Guid ApplicationID { get; set; }
        public string InvoiceDate { get; set; }
        public string SystemEntryDate { get; set; }
        public string InvoiceNo { get; set; }
        public string GrossTotal { get; set; }
        public string Hash { get; set; }
        public string Message { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
