//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auOptInOptOutTrace
    {
        public System.Guid OptInOptOutTraceID { get; set; }
        public System.Guid CommunicationID { get; set; }
        public System.DateTime OperationDate { get; set; }
        public string CompanyBrandCode { get; set; }
        public byte StatusType { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public Nullable<System.Guid> SubCurrAccID { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public string CommunicationTypeCode { get; set; }
        public string CommAddress { get; set; }
        public string FormNumber { get; set; }
        public string OptDescription { get; set; }
        public decimal CompanyCode { get; set; }
        public string OfficeCode { get; set; }
        public byte StoreTypeCode { get; set; }
        public string StoreCode { get; set; }
        public string UserName { get; set; }
        public string IdentificationMark { get; set; }
        public string MessageResponseID { get; set; }
        public string PermissionMarketingServiceCode { get; set; }
        public string PermissionMarketingServiceUID { get; set; }
        public bool SMS { get; set; }
        public bool Call { get; set; }
        public bool Email { get; set; }
        public string ConsentSource { get; set; }
        public System.DateTime ConsentTime { get; set; }
        public byte RecipientType { get; set; }
        public bool IsSentToBusinessPartner { get; set; }
        public System.DateTime SentDate { get; set; }
        public string MMSBusinessPartnerCode { get; set; }
        public string TransactionID { get; set; }
        public string ConfirmationFormTypeCode { get; set; }
        public Nullable<System.Guid> CurrAccPersonalDataConfirmationID { get; set; }
    
        public virtual cdCommunicationType cdCommunicationType { get; set; }
        public virtual cdCompanyBrand cdCompanyBrand { get; set; }
        public virtual cdCompany cdCompany { get; set; }
        public virtual cdConfirmationFormType cdConfirmationFormType { get; set; }
        public virtual cdOffice cdOffice { get; set; }
        public virtual cdPermissionMarketingService cdPermissionMarketingService { get; set; }
        public virtual cdCurrAcc cdCurrAcc { get; set; }
    }
}
