//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auWebTelZATCATransactionInfo
    {
        public System.Guid WebTelZATCATransactionInfoID { get; set; }
        public System.Guid V3TransactionID { get; set; }
        public int InvoiceID { get; set; }
        public string QRString { get; set; }
        public Nullable<System.Guid> UUID { get; set; }
        public string InvoiceXML { get; set; }
        public string InvoiceHash { get; set; }
        public int Status { get; set; }
        public string UniqueKey { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
