//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMTemplateAttributes
    {
        public string BOMTemplateCode { get; set; }
        public string BOMTemplateAtt01 { get; set; }
        public string BOMTemplateAtt02 { get; set; }
        public string BOMTemplateAtt03 { get; set; }
        public string BOMTemplateAtt04 { get; set; }
        public string BOMTemplateAtt05 { get; set; }
    }
}
