//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsAirportIATA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bsAirportIATA()
        {
            this.bsAirportIATADesc = new HashSet<bsAirportIATADesc>();
            this.tpInvoicePassportAndBoardingInfo = new HashSet<tpInvoicePassportAndBoardingInfo>();
            this.tpInvoicePassportAndBoardingInfo1 = new HashSet<tpInvoicePassportAndBoardingInfo>();
        }
    
        public string AirportIATACode { get; set; }
        public bool IsBlocked { get; set; }
        public System.Guid RowGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bsAirportIATADesc> bsAirportIATADesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpInvoicePassportAndBoardingInfo> tpInvoicePassportAndBoardingInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpInvoicePassportAndBoardingInfo> tpInvoicePassportAndBoardingInfo1 { get; set; }
    }
}
