//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsBulkMailServiceProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bsBulkMailServiceProvider()
        {
            this.bsBulkMailServiceProviderDesc = new HashSet<bsBulkMailServiceProviderDesc>();
            this.dfBulkMailServiceProviderAccount = new HashSet<dfBulkMailServiceProviderAccount>();
            this.dfCompanyDefault = new HashSet<dfCompanyDefault>();
            this.dfOfficeDefault = new HashSet<dfOfficeDefault>();
        }
    
        public byte BulkMailServiceProviderCode { get; set; }
        public bool IsBlocked { get; set; }
        public System.Guid RowGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bsBulkMailServiceProviderDesc> bsBulkMailServiceProviderDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfBulkMailServiceProviderAccount> dfBulkMailServiceProviderAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfCompanyDefault> dfCompanyDefault { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfOfficeDefault> dfOfficeDefault { get; set; }
    }
}
