//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsCostingLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bsCostingLevel()
        {
            this.bsCostingLevelDesc = new HashSet<bsCostingLevelDesc>();
            this.dfCompanyCostOfGoodsSold = new HashSet<dfCompanyCostOfGoodsSold>();
            this.trCostOfGoodsSoldHeader = new HashSet<trCostOfGoodsSoldHeader>();
        }
    
        public byte CostingLevelCode { get; set; }
        public bool IsBlocked { get; set; }
        public System.Guid RowGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bsCostingLevelDesc> bsCostingLevelDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfCompanyCostOfGoodsSold> dfCompanyCostOfGoodsSold { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trCostOfGoodsSoldHeader> trCostOfGoodsSoldHeader { get; set; }
    }
}
