//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsCustomsProductGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bsCustomsProductGroup()
        {
            this.bsCustomsProductGroupDesc = new HashSet<bsCustomsProductGroupDesc>();
            this.cdItem = new HashSet<cdItem>();
        }
    
        public byte CustomsProductGroupCode { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public bool IsLimitedSaleProduct { get; set; }
        public double DepartureStoreLimit { get; set; }
        public double ArrivalStoreLimit { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual cdUnitOfMeasure cdUnitOfMeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bsCustomsProductGroupDesc> bsCustomsProductGroupDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdItem> cdItem { get; set; }
    }
}
