//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bsDevice()
        {
            this.bsDeviceDesc = new HashSet<bsDeviceDesc>();
            this.dfPosDeviceParameters = new HashSet<dfPosDeviceParameters>();
            this.prPaymentProviderConvert = new HashSet<prPaymentProviderConvert>();
            this.prPosTerminalDevice = new HashSet<prPosTerminalDevice>();
        }
    
        public byte DeviceCode { get; set; }
        public byte DeviceTypeCode { get; set; }
        public string ClassLibraryName { get; set; }
        public bool IsOKC { get; set; }
        public bool IsBlocked { get; set; }
        public System.Guid RowGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bsDeviceDesc> bsDeviceDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfPosDeviceParameters> dfPosDeviceParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prPaymentProviderConvert> prPaymentProviderConvert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prPosTerminalDevice> prPosTerminalDevice { get; set; }
    }
}
