//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsEasyStartupSteps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bsEasyStartupSteps()
        {
            this.bsEasyStartupStepsDesc = new HashSet<bsEasyStartupStepsDesc>();
            this.prEasyStartupComments = new HashSet<prEasyStartupComments>();
            this.prEasyStartupNotes = new HashSet<prEasyStartupNotes>();
        }
    
        public int EasyStartupStepCode { get; set; }
        public bool IsCompleted { get; set; }
        public System.Guid RowGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bsEasyStartupStepsDesc> bsEasyStartupStepsDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prEasyStartupComments> prEasyStartupComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prEasyStartupNotes> prEasyStartupNotes { get; set; }
    }
}
