//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsEditMask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bsEditMask()
        {
            this.bsEditMaskDesc = new HashSet<bsEditMaskDesc>();
            this.cdCommunicationType = new HashSet<cdCommunicationType>();
            this.cdCreditCardType = new HashSet<cdCreditCardType>();
        }
    
        public int EditMaskCode { get; set; }
        public string EditMask { get; set; }
        public string Sample { get; set; }
        public byte CommunicationKindCode { get; set; }
        public bool IsBlocked { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual bsCommunicationKind bsCommunicationKind { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bsEditMaskDesc> bsEditMaskDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdCommunicationType> cdCommunicationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdCreditCardType> cdCreditCardType { get; set; }
    }
}
