//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsExpenseSlipType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bsExpenseSlipType()
        {
            this.auExpenseSlipPermit = new HashSet<auExpenseSlipPermit>();
            this.bsExpenseSlipTypeDesc = new HashSet<bsExpenseSlipTypeDesc>();
            this.dfExpenseSlipForm = new HashSet<dfExpenseSlipForm>();
            this.trExpenseSlipHeader = new HashSet<trExpenseSlipHeader>();
        }
    
        public byte ExpenseSlipTypeCode { get; set; }
        public bool IsBlocked { get; set; }
        public System.Guid RowGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auExpenseSlipPermit> auExpenseSlipPermit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bsExpenseSlipTypeDesc> bsExpenseSlipTypeDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfExpenseSlipForm> dfExpenseSlipForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trExpenseSlipHeader> trExpenseSlipHeader { get; set; }
    }
}
