//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bsSGKWorkPlaceSector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bsSGKWorkPlaceSector()
        {
            this.bsSGKWorkPlaceSectorDesc = new HashSet<bsSGKWorkPlaceSectorDesc>();
            this.cdWorkPlace = new HashSet<cdWorkPlace>();
        }
    
        public string SGKWorkPlaceSectorCode { get; set; }
        public bool IsCompleted { get; set; }
        public System.Guid RowGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bsSGKWorkPlaceSectorDesc> bsSGKWorkPlaceSectorDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdWorkPlace> cdWorkPlace { get; set; }
    }
}
