//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdColor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdColor()
        {
            this.cdPantone = new HashSet<cdPantone>();
            this.cdColorDesc = new HashSet<cdColorDesc>();
            this.prItemColorAttributes = new HashSet<prItemColorAttributes>();
            this.prItemColorFabricBlend = new HashSet<prItemColorFabricBlend>();
            this.prItemListContent = new HashSet<prItemListContent>();
            this.prItemTextileCareSymbol = new HashSet<prItemTextileCareSymbol>();
            this.prItemVariant = new HashSet<prItemVariant>();
            this.prLinkedProductContentSumDetail = new HashSet<prLinkedProductContentSumDetail>();
            this.prMarketPlaceProduct = new HashSet<prMarketPlaceProduct>();
            this.prProductColorAttribute = new HashSet<prProductColorAttribute>();
            this.prProductColorSetContent = new HashSet<prProductColorSetContent>();
            this.prProductImageURLs = new HashSet<prProductImageURLs>();
            this.prProductLot = new HashSet<prProductLot>();
            this.prProductLotBarcode = new HashSet<prProductLotBarcode>();
            this.trAllocationProduct = new HashSet<trAllocationProduct>();
            this.trInnerLineSumDetail = new HashSet<trInnerLineSumDetail>();
            this.trInnerOrderLineSumDetail = new HashSet<trInnerOrderLineSumDetail>();
            this.trInvoiceLineSumDetail = new HashSet<trInvoiceLineSumDetail>();
            this.trOrderAsnLineSumDetail = new HashSet<trOrderAsnLineSumDetail>();
            this.trOrderLineSumDetail = new HashSet<trOrderLineSumDetail>();
            this.trPriceListLine = new HashSet<trPriceListLine>();
            this.trProposalLineSumDetail = new HashSet<trProposalLineSumDetail>();
            this.trSalesPlanProductQty = new HashSet<trSalesPlanProductQty>();
            this.trShipmentLineSumDetail = new HashSet<trShipmentLineSumDetail>();
            this.trTransferPlanProduct = new HashSet<trTransferPlanProduct>();
            this.trVendorPriceListLine = new HashSet<trVendorPriceListLine>();
        }
    
        public string ColorCode { get; set; }
        public string ColorHex { get; set; }
        public string ColorCatalogCode1 { get; set; }
        public string ColorCatalogCode2 { get; set; }
        public string ColorCatalogCode3 { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual cdColorCatalog cdColorCatalog { get; set; }
        public virtual cdColorCatalog cdColorCatalog1 { get; set; }
        public virtual cdColorCatalog cdColorCatalog2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdPantone> cdPantone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdColorDesc> cdColorDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prItemColorAttributes> prItemColorAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prItemColorFabricBlend> prItemColorFabricBlend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prItemListContent> prItemListContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prItemTextileCareSymbol> prItemTextileCareSymbol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prItemVariant> prItemVariant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prLinkedProductContentSumDetail> prLinkedProductContentSumDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prMarketPlaceProduct> prMarketPlaceProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prProductColorAttribute> prProductColorAttribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prProductColorSetContent> prProductColorSetContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prProductImageURLs> prProductImageURLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prProductLot> prProductLot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prProductLotBarcode> prProductLotBarcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trAllocationProduct> trAllocationProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trInnerLineSumDetail> trInnerLineSumDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trInnerOrderLineSumDetail> trInnerOrderLineSumDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trInvoiceLineSumDetail> trInvoiceLineSumDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trOrderAsnLineSumDetail> trOrderAsnLineSumDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trOrderLineSumDetail> trOrderLineSumDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trPriceListLine> trPriceListLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trProposalLineSumDetail> trProposalLineSumDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trSalesPlanProductQty> trSalesPlanProductQty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trShipmentLineSumDetail> trShipmentLineSumDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trTransferPlanProduct> trTransferPlanProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trVendorPriceListLine> trVendorPriceListLine { get; set; }
    }
}
