//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdConfirmationFormType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdConfirmationFormType()
        {
            this.auOptInOptOutTrace = new HashSet<auOptInOptOutTrace>();
            this.cdConfirmationFormTypeDesc = new HashSet<cdConfirmationFormTypeDesc>();
            this.dfCompanyDefault = new HashSet<dfCompanyDefault>();
            this.dfOfficeDefault = new HashSet<dfOfficeDefault>();
            this.prConfirmationFormCommTypes = new HashSet<prConfirmationFormCommTypes>();
            this.prConfirmationFormContent = new HashSet<prConfirmationFormContent>();
            this.prCurrAccOptInOptOutStatus = new HashSet<prCurrAccOptInOptOutStatus>();
            this.prCurrAccPersonalDataConfirmation = new HashSet<prCurrAccPersonalDataConfirmation>();
            this.prCustomerPresentCard = new HashSet<prCustomerPresentCard>();
            this.prPersonalDataConfirmationFormTypeForCurrAccTypes = new HashSet<prPersonalDataConfirmationFormTypeForCurrAccTypes>();
            this.prPresentCardActivationSteps = new HashSet<prPresentCardActivationSteps>();
            this.srRefNumberConfirmationForm = new HashSet<srRefNumberConfirmationForm>();
        }
    
        public string ConfirmationFormTypeCode { get; set; }
        public string FormName { get; set; }
        public bool UseForCommunication { get; set; }
        public bool UseForPresentCard { get; set; }
        public bool UsePreprintedForm { get; set; }
        public bool UseSameCardNumberWithFormNumber { get; set; }
        public bool UseForPersonalData { get; set; }
        public bool DoNotRequestReConfirmation { get; set; }
        public bool IsBlocked { get; set; }
        public string FormNumberPrefix { get; set; }
        public bool UseSMS { get; set; }
        public bool UsePreConfiguredOptions { get; set; }
        public bool CanShareWithThirdParty { get; set; }
        public bool CanShareWithForeignCountries { get; set; }
        public bool CallPermission { get; set; }
        public bool SmsPermission { get; set; }
        public bool EmailPermission { get; set; }
        public bool AddressPermission { get; set; }
        public string ConfirmationFormStatusCode { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public bool UseSMSWithCustomerInformation { get; set; }
        public string ConsentSource { get; set; }
        public bool DataProcessPermission { get; set; }
        public bool OptOutCommunicationsWithPDCInactivation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auOptInOptOutTrace> auOptInOptOutTrace { get; set; }
        public virtual bsConsentSource bsConsentSource { get; set; }
        public virtual cdConfirmationFormStatus cdConfirmationFormStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdConfirmationFormTypeDesc> cdConfirmationFormTypeDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfCompanyDefault> dfCompanyDefault { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfOfficeDefault> dfOfficeDefault { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prConfirmationFormCommTypes> prConfirmationFormCommTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prConfirmationFormContent> prConfirmationFormContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prCurrAccOptInOptOutStatus> prCurrAccOptInOptOutStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prCurrAccPersonalDataConfirmation> prCurrAccPersonalDataConfirmation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prCustomerPresentCard> prCustomerPresentCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prPersonalDataConfirmationFormTypeForCurrAccTypes> prPersonalDataConfirmationFormTypeForCurrAccTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prPresentCardActivationSteps> prPresentCardActivationSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<srRefNumberConfirmationForm> srRefNumberConfirmationForm { get; set; }
    }
}
