//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdDeclaration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdDeclaration()
        {
            this.cdDeclarationDesc = new HashSet<cdDeclarationDesc>();
        }
    
        public decimal CompanyCode { get; set; }
        public string DeclarationCode { get; set; }
        public byte DeclarationTypeCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public byte DeclarationCapacityCode { get; set; }
        public string AccountantCode1 { get; set; }
        public string AccountantCode2 { get; set; }
        public string AccountantCode3 { get; set; }
        public string AccountantCode4 { get; set; }
        public decimal Assessment { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual bsDeclarationCapacity bsDeclarationCapacity { get; set; }
        public virtual bsDeclarationType bsDeclarationType { get; set; }
        public virtual cdAccountant cdAccountant { get; set; }
        public virtual cdAccountant cdAccountant1 { get; set; }
        public virtual cdAccountant cdAccountant2 { get; set; }
        public virtual cdAccountant cdAccountant3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdDeclarationDesc> cdDeclarationDesc { get; set; }
        public virtual prDeclarationXML prDeclarationXML { get; set; }
    }
}
