//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdItemDim1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdItemDim1()
        {
            this.cdItemDim1Desc = new HashSet<cdItemDim1Desc>();
            this.prItemVariant = new HashSet<prItemVariant>();
            this.prLotQty = new HashSet<prLotQty>();
            this.prMarketPlaceProduct = new HashSet<prMarketPlaceProduct>();
            this.prProductDimSetContent = new HashSet<prProductDimSetContent>();
            this.trPriceListLine = new HashSet<trPriceListLine>();
            this.trVendorPriceListLine = new HashSet<trVendorPriceListLine>();
        }
    
        public string ItemDim1Code { get; set; }
        public string ItemDimType1 { get; set; }
        public string ItemDimType2 { get; set; }
        public string ItemDimType3 { get; set; }
        public string ItemDimType4 { get; set; }
        public string ItemDimType5 { get; set; }
        public string ItemDimType6 { get; set; }
        public string ItemDimType7 { get; set; }
        public string ItemDimType8 { get; set; }
        public string ItemDimType9 { get; set; }
        public string ItemDimType10 { get; set; }
        public short SortOrder { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdItemDim1Desc> cdItemDim1Desc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prItemVariant> prItemVariant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prLotQty> prLotQty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prMarketPlaceProduct> prMarketPlaceProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prProductDimSetContent> prProductDimSetContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trPriceListLine> trPriceListLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trVendorPriceListLine> trVendorPriceListLine { get; set; }
    }
}
