//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdItemOTAttribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdItemOTAttribute()
        {
            this.cdItemOTAttributeDesc = new HashSet<cdItemOTAttributeDesc>();
            this.tpOrderOTAttribute = new HashSet<tpOrderOTAttribute>();
        }
    
        public byte ItemTypeCode { get; set; }
        public byte AttributeTypeCode { get; set; }
        public string AttributeCode { get; set; }
        public string ProductHierarchyFilter { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public string Description { get; set; }
    
        public virtual cdItemOTAttributeType cdItemOTAttributeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdItemOTAttributeDesc> cdItemOTAttributeDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpOrderOTAttribute> tpOrderOTAttribute { get; set; }
    }
}
