//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdItemAttribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdItemAttribute()
        {
            this.cdBOMTemplateAttribute = new HashSet<cdBOMTemplateAttribute>();
            this.cdItemAttributeDesc = new HashSet<cdItemAttributeDesc>();
            this.dfProductHierarchyAttribute = new HashSet<dfProductHierarchyAttribute>();
            this.prItemAttribute = new HashSet<prItemAttribute>();
        }
    
        public byte ItemTypeCode { get; set; }
        public byte AttributeTypeCode { get; set; }
        public string AttributeCode { get; set; }
        public string ProductHierarchyFilter { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdBOMTemplateAttribute> cdBOMTemplateAttribute { get; set; }
        public virtual cdItemAttributeType cdItemAttributeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdItemAttributeDesc> cdItemAttributeDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfProductHierarchyAttribute> dfProductHierarchyAttribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prItemAttribute> prItemAttribute { get; set; }
    }
}
