//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdMMSBusinessPartnerService
    {
        public decimal CompanyCode { get; set; }
        public string MMSBusinessPartnerCode { get; set; }
        public string Gateway { get; set; }
        public string PlatformID { get; set; }
        public string ChannelCode { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ApiKey { get; set; }
        public string Secret { get; set; }
        public string CollectorID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual bsMMSBusinessPartner bsMMSBusinessPartner { get; set; }
        public virtual cdCompany cdCompany { get; set; }
    }
}
