//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdOpticalSut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdOpticalSut()
        {
            this.cdOpticalSutDesc = new HashSet<cdOpticalSutDesc>();
            this.prOpticalSutContributionAmount = new HashSet<prOpticalSutContributionAmount>();
            this.prProductFrameProperties = new HashSet<prProductFrameProperties>();
            this.prProductLensProperties = new HashSet<prProductLensProperties>();
            this.tpInvoiceLineOpticalProductInfo = new HashSet<tpInvoiceLineOpticalProductInfo>();
            this.trOrderOpticalProductLine = new HashSet<trOrderOpticalProductLine>();
        }
    
        public string OpticalSutCode { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public byte EyeGlassSutTypeCode { get; set; }
        public double MinSphere { get; set; }
        public double MaxSphere { get; set; }
        public double MinCylinder { get; set; }
        public double MaxCylinder { get; set; }
    
        public virtual bsEyeGlassSutType bsEyeGlassSutType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdOpticalSutDesc> cdOpticalSutDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prOpticalSutContributionAmount> prOpticalSutContributionAmount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prProductFrameProperties> prProductFrameProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prProductLensProperties> prProductLensProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpInvoiceLineOpticalProductInfo> tpInvoiceLineOpticalProductInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trOrderOpticalProductLine> trOrderOpticalProductLine { get; set; }
    }
}
