//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdPaymentProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdPaymentProvider()
        {
            this.cdPaymentProviderDesc = new HashSet<cdPaymentProviderDesc>();
            this.prDiscountOfferPaymentProvider = new HashSet<prDiscountOfferPaymentProvider>();
            this.prPaymentProviderConvert = new HashSet<prPaymentProviderConvert>();
            this.prPaymentProviderGLAccs = new HashSet<prPaymentProviderGLAccs>();
            this.tpOrderDistanceSalesCorrelations = new HashSet<tpOrderDistanceSalesCorrelations>();
            this.trCreditCardPaymentLine = new HashSet<trCreditCardPaymentLine>();
            this.trOtherPaymentHeader = new HashSet<trOtherPaymentHeader>();
            this.prUniFreeTenderTypeMapping = new HashSet<prUniFreeTenderTypeMapping>();
        }
    
        public string PaymentProviderCode { get; set; }
        public bool IsCreditCardProvider { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public string DiscountPointTypeCode { get; set; }
        public bool IsOKCApplication { get; set; }
    
        public virtual cdDiscountPointType cdDiscountPointType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdPaymentProviderDesc> cdPaymentProviderDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prDiscountOfferPaymentProvider> prDiscountOfferPaymentProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prPaymentProviderConvert> prPaymentProviderConvert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prPaymentProviderGLAccs> prPaymentProviderGLAccs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpOrderDistanceSalesCorrelations> tpOrderDistanceSalesCorrelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trCreditCardPaymentLine> trCreditCardPaymentLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trOtherPaymentHeader> trOtherPaymentHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prUniFreeTenderTypeMapping> prUniFreeTenderTypeMapping { get; set; }
    }
}
