//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdPermissionMarketingService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdPermissionMarketingService()
        {
            this.auOptInOptOutTrace = new HashSet<auOptInOptOutTrace>();
            this.dfCompanyDefault = new HashSet<dfCompanyDefault>();
            this.dfMobildevStoreCollectorID = new HashSet<dfMobildevStoreCollectorID>();
            this.prCurrAccPersonalDataConfirmation = new HashSet<prCurrAccPersonalDataConfirmation>();
        }
    
        public decimal CompanyCode { get; set; }
        public string PermissionMarketingServiceCode { get; set; }
        public string PermissionMarketingServiceDescription { get; set; }
        public string Gateway { get; set; }
        public string ApiKey { get; set; }
        public string Secret { get; set; }
        public string OptInCollectorID { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string CustomerCode { get; set; }
        public byte OptInType { get; set; }
        public byte OptInMethod { get; set; }
        public string OptOutCollectorID { get; set; }
        public byte OptOutType { get; set; }
        public byte OptOutMethod { get; set; }
        public int BrandID { get; set; }
        public string SyncServiceCollectorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auOptInOptOutTrace> auOptInOptOutTrace { get; set; }
        public virtual cdCompany cdCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfCompanyDefault> dfCompanyDefault { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfMobildevStoreCollectorID> dfMobildevStoreCollectorID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prCurrAccPersonalDataConfirmation> prCurrAccPersonalDataConfirmation { get; set; }
    }
}
