//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdRequisition()
        {
            this.cdProposalConfirmationLimit = new HashSet<cdProposalConfirmationLimit>();
            this.cdProposalConfirmationRule = new HashSet<cdProposalConfirmationRule>();
            this.cdRequisitionConfirmationLimit = new HashSet<cdRequisitionConfirmationLimit>();
            this.cdRequisitionConfirmationRule = new HashSet<cdRequisitionConfirmationRule>();
            this.cdRequisitionDesc = new HashSet<cdRequisitionDesc>();
            this.prItemRequisition = new HashSet<prItemRequisition>();
            this.prPurchasingAgentAvailableRequisition = new HashSet<prPurchasingAgentAvailableRequisition>();
            this.prRequisitionAttribute = new HashSet<prRequisitionAttribute>();
            this.prRequisitionCurrAcc = new HashSet<prRequisitionCurrAcc>();
            this.prRequisitionLimit = new HashSet<prRequisitionLimit>();
            this.prTechnicalResponsibleAvailableRequisition = new HashSet<prTechnicalResponsibleAvailableRequisition>();
            this.trPurchaseRequisitionLine = new HashSet<trPurchaseRequisitionLine>();
        }
    
        public string RequisitionCode { get; set; }
        public Nullable<byte> ItemTypeCode { get; set; }
        public string RequisitionTypeCode { get; set; }
        public string AveragePriceCurrencyCode { get; set; }
        public decimal AveragePrice { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public bool IsProposalRequired { get; set; }
        public byte MinProposalCount { get; set; }
    
        public virtual bsItemType bsItemType { get; set; }
        public virtual cdCurrency cdCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdProposalConfirmationLimit> cdProposalConfirmationLimit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdProposalConfirmationRule> cdProposalConfirmationRule { get; set; }
        public virtual cdRequisitionType cdRequisitionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdRequisitionConfirmationLimit> cdRequisitionConfirmationLimit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdRequisitionConfirmationRule> cdRequisitionConfirmationRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdRequisitionDesc> cdRequisitionDesc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prItemRequisition> prItemRequisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prPurchasingAgentAvailableRequisition> prPurchasingAgentAvailableRequisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prRequisitionAttribute> prRequisitionAttribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prRequisitionCurrAcc> prRequisitionCurrAcc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prRequisitionLimit> prRequisitionLimit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prTechnicalResponsibleAvailableRequisition> prTechnicalResponsibleAvailableRequisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trPurchaseRequisitionLine> trPurchaseRequisitionLine { get; set; }
    }
}
