//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdRoll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdRoll()
        {
            this.prRollNotes = new HashSet<prRollNotes>();
            this.stItemRollNumber = new HashSet<stItemRollNumber>();
            this.stItemRollNumberPicking = new HashSet<stItemRollNumberPicking>();
        }
    
        public string RollNumber { get; set; }
        public byte ItemTypeCode { get; set; }
        public string ItemCode { get; set; }
        public string ColorCode { get; set; }
        public string ItemDim1Code { get; set; }
        public string ItemDim2Code { get; set; }
        public string ItemDim3Code { get; set; }
        public string BatchCode { get; set; }
        public string BatchGroupCode { get; set; }
        public string OriginalBarcode { get; set; }
        public double Width { get; set; }
        public double M2Gramaj { get; set; }
        public string WarehouseCode { get; set; }
        public string SectionCode { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual cdBatch cdBatch { get; set; }
        public virtual cdBatchGroup cdBatchGroup { get; set; }
        public virtual prItemVariant prItemVariant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prRollNotes> prRollNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stItemRollNumber> stItemRollNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stItemRollNumberPicking> stItemRollNumberPicking { get; set; }
    }
}
