//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdStreet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdStreet()
        {
            this.bsTaxFreeRefundCompany = new HashSet<bsTaxFreeRefundCompany>();
            this.cdPort = new HashSet<cdPort>();
            this.cdWorkPlace = new HashSet<cdWorkPlace>();
            this.dfCompanyDefault = new HashSet<dfCompanyDefault>();
            this.dfOfficeDefault = new HashSet<dfOfficeDefault>();
            this.prCurrAccPostalAddress = new HashSet<prCurrAccPostalAddress>();
            this.prResponsibilityAreaPostalAddress = new HashSet<prResponsibilityAreaPostalAddress>();
            this.prWarehousePostalAddress = new HashSet<prWarehousePostalAddress>();
            this.tpInvoicePostalAddress = new HashSet<tpInvoicePostalAddress>();
            this.tpOrderPostalAddress = new HashSet<tpOrderPostalAddress>();
        }
    
        public string DistrictCode { get; set; }
        public int QuarterCode { get; set; }
        public int StreetCode { get; set; }
        public string Street { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bsTaxFreeRefundCompany> bsTaxFreeRefundCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdPort> cdPort { get; set; }
        public virtual cdQuarter cdQuarter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdWorkPlace> cdWorkPlace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfCompanyDefault> dfCompanyDefault { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dfOfficeDefault> dfOfficeDefault { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prCurrAccPostalAddress> prCurrAccPostalAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prResponsibilityAreaPostalAddress> prResponsibilityAreaPostalAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prWarehousePostalAddress> prWarehousePostalAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpInvoicePostalAddress> tpInvoicePostalAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpOrderPostalAddress> tpOrderPostalAddress { get; set; }
    }
}
