//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdUniFreeTenderType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdUniFreeTenderType()
        {
            this.prUniFreeTenderTypeMapping = new HashSet<prUniFreeTenderTypeMapping>();
        }
    
        public string TenderTypeCode { get; set; }
        public string TenderTypeDescription { get; set; }
        public byte PaymentMethod { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public string CurrencyCode { get; set; }
        public byte ExchangeTypeCode { get; set; }
    
        public virtual cdCurrency cdCurrency { get; set; }
        public virtual cdExchangeType cdExchangeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prUniFreeTenderTypeMapping> prUniFreeTenderTypeMapping { get; set; }
    }
}
