//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeOrderList
    {
        public System.Guid RowID { get; set; }
        public System.DateTime OperationDate { get; set; }
        public string ProcessCode { get; set; }
        public string CustomerCode { get; set; }
        public string FirstLastName { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CompanyCode { get; set; }
        public string OfficeCode { get; set; }
        public string StoreCode { get; set; }
        public string WarehouseCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductDescription { get; set; }
        public string ColorCode { get; set; }
        public string ColorDescription { get; set; }
        public string ItemDim1Code { get; set; }
        public string ItemDim2Code { get; set; }
        public double OrderQty1 { get; set; }
        public decimal NetAmount { get; set; }
        public System.Guid OrderHeaderID { get; set; }
        public System.Guid OrderLineID { get; set; }
        public byte PaymentTypeCode { get; set; }
        public string PaymentCode { get; set; }
        public string PaymentDescription { get; set; }
        public Nullable<System.Guid> NewOrderHeaderID { get; set; }
    }
}
