//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFilter
    {
        public string CustomerCode { get; set; }
        public byte CustomerTypeCode { get; set; }
        public bool IsVIP { get; set; }
        public string WholesalePriceGroupCode { get; set; }
        public string PromotionGroupCode { get; set; }
        public string SalesChannelCode { get; set; }
        public string CustomerDiscountGrCode { get; set; }
        public decimal CompanyCode { get; set; }
        public string OfficeCode { get; set; }
        public string OfficeCountryCode { get; set; }
        public System.DateTime AccountOpeningDate { get; set; }
        public string CustomerAtt01 { get; set; }
        public string CustomerAtt02 { get; set; }
        public string CustomerAtt03 { get; set; }
        public string CustomerAtt04 { get; set; }
        public string CustomerAtt05 { get; set; }
        public string CustomerAtt06 { get; set; }
        public string CustomerAtt07 { get; set; }
        public string CustomerAtt08 { get; set; }
        public string CustomerAtt09 { get; set; }
        public string CustomerAtt10 { get; set; }
        public string CustomerAtt11 { get; set; }
        public string CustomerAtt12 { get; set; }
        public string CustomerAtt13 { get; set; }
        public string CustomerAtt14 { get; set; }
        public string CustomerAtt15 { get; set; }
        public string TitleCode { get; set; }
    }
}
