//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataTransferTemplateQueryFilter
    {
        public int DataTransferTemplateQueryFilterID { get; set; }
        public string TransferName { get; set; }
        public string ElementName { get; set; }
        public string FilterName { get; set; }
    }
}
