//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dfGuidedSalesCustomerParameters
    {
        public System.Guid GuidedSalesCustomerParametersID { get; set; }
        public string VisibleCurrAccAttTypes { get; set; }
        public string VisibleCustomerCompanyBrandAttTypes { get; set; }
        public Nullable<byte> CurrAccAttTypeForMonetaryValue { get; set; }
        public string CurrAccAttCodeForMonetaryLowValue { get; set; }
        public string CurrAccAttCodeForMonetaryHighValue { get; set; }
        public Nullable<byte> CustomerCompanyBrandAttTypeForMonetaryValue { get; set; }
        public string CustomerCompanyBrandAttCodeForMonetaryLowValue { get; set; }
        public string CustomerCompanyBrandAttCodeForMonetaryHighValue { get; set; }
        public Nullable<byte> CurrAccAttTypeForBehavioralValue { get; set; }
        public string CurrAccAttCodeForBehavioralLowValue { get; set; }
        public string CurrAccAttCodeForBehavioralHighValue { get; set; }
        public Nullable<byte> CustomerCompanyBrandAttTypeForBehavioralValue { get; set; }
        public string CustomerCompanyBrandAttCodeForBehavioralLowValue { get; set; }
        public string CustomerCompanyBrandAttCodeForBehavioralHighValue { get; set; }
        public string EmailCommunicationTypeCode { get; set; }
        public string MobileCommunicationTypeCode { get; set; }
        public Nullable<bool> CustomerInformationCannotBeChanged { get; set; }
        public Nullable<bool> ShowCustomerAlertColor { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public Nullable<byte> BeforeBirthDate { get; set; }
        public Nullable<byte> AfterBirthDate { get; set; }
        public Nullable<byte> BeforeMarriedDate { get; set; }
        public Nullable<byte> AfterMarriedDate { get; set; }
        public Nullable<bool> UseSMSVerificationOnMS { get; set; }
        public Nullable<bool> UseSMSVerificationOnMSForValidDiscounts { get; set; }
        public string DefRetailCustomerCodeMobileStore { get; set; }
        public bool UseAlwaysDefRetailCustomerMobileStore { get; set; }
    }
}
