//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_InboxInvoiceLine
    {
        public System.Guid UUID { get; set; }
        public int SortOrder { get; set; }
        public string Note { get; set; }
        public string ItemDescription { get; set; }
        public string ItemName { get; set; }
        public string BrandName { get; set; }
        public string ModelName { get; set; }
        public string BuyersItemIdentification { get; set; }
        public string SellersItemIdentification { get; set; }
        public string ItemClassificationCode { get; set; }
        public string ManufacturersItemIdentification { get; set; }
        public byte RecordedItemTypeCode { get; set; }
        public string RecordedItemCode { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public double InvoicedQuantity { get; set; }
        public string CurrencyCode { get; set; }
        public double ExchangeRate { get; set; }
        public decimal LineExtensionAmount { get; set; }
        public decimal TaxExclusiveAmount { get; set; }
        public decimal TaxInclusiveAmount { get; set; }
        public decimal AllowanceTotal { get; set; }
        public float KDVRate { get; set; }
        public decimal KDV { get; set; }
        public string OTVTaxTypeCode { get; set; }
        public float OTVRate { get; set; }
        public decimal OTV { get; set; }
        public double LDisRate1 { get; set; }
        public double LDisRate2 { get; set; }
        public double LDisRate3 { get; set; }
        public double LDisRate4 { get; set; }
        public double LDisRate5 { get; set; }
        public decimal LDiscount1 { get; set; }
        public decimal LDiscount2 { get; set; }
        public decimal LDiscount3 { get; set; }
        public decimal LDiscount4 { get; set; }
        public decimal LDiscount5 { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string TevkifatKodu { get; set; }
        public double Tevkifat { get; set; }
    
        public virtual e_InboxInvoiceHeader e_InboxInvoiceHeader { get; set; }
    }
}
