//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_InboxShipmentHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public e_InboxShipmentHeader()
        {
            this.e_InboxShipmentDrivers = new HashSet<e_InboxShipmentDrivers>();
            this.e_InboxShipmentLine = new HashSet<e_InboxShipmentLine>();
        }
    
        public decimal CompanyCode { get; set; }
        public System.Guid UUID { get; set; }
        public string ID { get; set; }
        public string CopyIndicator { get; set; }
        public string ProfileID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime IssueTime { get; set; }
        public string DespatchAdviceTypeCode { get; set; }
        public System.DateTime ActualDate { get; set; }
        public System.DateTime ActualTime { get; set; }
        public string Note { get; set; }
        public string URNAddress { get; set; }
        public string ApplicationCode { get; set; }
        public byte InboxShipmentStatusCode { get; set; }
        public long EFinansDocumentSerialNumber { get; set; }
        public Nullable<System.Guid> CreatedHeaderID { get; set; }
    
        public virtual e_InboxShipmentBuyerCustomerParty e_InboxShipmentBuyerCustomerParty { get; set; }
        public virtual e_InboxShipmentCarrierParty e_InboxShipmentCarrierParty { get; set; }
        public virtual e_InboxShipmentDeliveryCustomerParty e_InboxShipmentDeliveryCustomerParty { get; set; }
        public virtual e_InboxShipmentDespatchSupplierParty e_InboxShipmentDespatchSupplierParty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<e_InboxShipmentDrivers> e_InboxShipmentDrivers { get; set; }
        public virtual e_InboxShipmentStatus e_InboxShipmentStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<e_InboxShipmentLine> e_InboxShipmentLine { get; set; }
        public virtual e_InboxShipmentOriginatorCustomerParty e_InboxShipmentOriginatorCustomerParty { get; set; }
        public virtual e_InboxShipmentSellerSupplierParty e_InboxShipmentSellerSupplierParty { get; set; }
        public virtual e_InboxShipmentTransportDetails e_InboxShipmentTransportDetails { get; set; }
    }
}
