//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_OutboxInvoiceLinePickingDetails
    {
        public System.Guid InvoiceLinePickingDetailsID { get; set; }
        public System.Guid UUID { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime PickingDate { get; set; }
        public string PackageNumber { get; set; }
        public string PackagingTypeCode { get; set; }
        public string PackageBrand { get; set; }
        public string PackageVolume { get; set; }
        public string WeightUnitOfMeasureCode { get; set; }
        public float PackedWeight { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public double Qty { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual e_OutboxInvoiceLine e_OutboxInvoiceLine { get; set; }
    }
}
