//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_OutboxInvoiceHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public e_OutboxInvoiceHeader()
        {
            this.e_OutboxInvoiceDespatch = new HashSet<e_OutboxInvoiceDespatch>();
            this.e_OutboxInvoiceHeaderExportSaleCharges = new HashSet<e_OutboxInvoiceHeaderExportSaleCharges>();
            this.e_OutboxInvoiceLine = new HashSet<e_OutboxInvoiceLine>();
            this.e_OutboxInvoiceOrder = new HashSet<e_OutboxInvoiceOrder>();
            this.e_OutboxInvoiceParty = new HashSet<e_OutboxInvoiceParty>();
            this.e_OutboxInvoiceUBLExtensions = new HashSet<e_OutboxInvoiceUBLExtensions>();
        }
    
        public short CompanyCode { get; set; }
        public System.Guid UUID { get; set; }
        public string ID { get; set; }
        public string CopyIndicator { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime IssueTime { get; set; }
        public string InvoiceTypeCode { get; set; }
        public string InvoiceNumber { get; set; }
        public string URNAddress { get; set; }
        public string Note { get; set; }
        public string DocumentCurrencyCode { get; set; }
        public double ExchangeRate { get; set; }
        public int LineCountNumeric { get; set; }
        public double TDisRate1 { get; set; }
        public double TDisRate2 { get; set; }
        public double TDisRate3 { get; set; }
        public double TDisRate4 { get; set; }
        public double TDisRate5 { get; set; }
        public decimal TDiscount1 { get; set; }
        public decimal TDiscount2 { get; set; }
        public decimal TDiscount3 { get; set; }
        public decimal TDiscount4 { get; set; }
        public decimal TDiscount5 { get; set; }
        public double StoppageRate { get; set; }
        public string TevkifatKodu { get; set; }
        public double Tevkifat { get; set; }
        public string TaxExemption { get; set; }
        public int InnerStatusCode { get; set; }
        public System.DateTime ConfirmedDate { get; set; }
        public string ConfirmedUserName { get; set; }
        public long IntegratorID { get; set; }
        public string IntegratorIDs { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsSimple { get; set; }
        public bool IsDone { get; set; }
        public bool IsFreeInvoice { get; set; }
        public byte OutboxStatusCode { get; set; }
        public string FromIntegrator_UUID { get; set; }
        public string FromIntegrator_ID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual e_OutboxInvoiceCurrAcc e_OutboxInvoiceCurrAcc { get; set; }
        public virtual e_OutboxInvoiceDelivery e_OutboxInvoiceDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<e_OutboxInvoiceDespatch> e_OutboxInvoiceDespatch { get; set; }
        public virtual e_OutboxStatus e_OutboxStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<e_OutboxInvoiceHeaderExportSaleCharges> e_OutboxInvoiceHeaderExportSaleCharges { get; set; }
        public virtual e_OutboxInvoiceHeaderExportSaleExtensions e_OutboxInvoiceHeaderExportSaleExtensions { get; set; }
        public virtual e_OutboxInvoiceHeaderExportSaleTransportDetails e_OutboxInvoiceHeaderExportSaleTransportDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<e_OutboxInvoiceLine> e_OutboxInvoiceLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<e_OutboxInvoiceOrder> e_OutboxInvoiceOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<e_OutboxInvoiceParty> e_OutboxInvoiceParty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<e_OutboxInvoiceUBLExtensions> e_OutboxInvoiceUBLExtensions { get; set; }
        public virtual e_OutboxInvoiceSGKExtensions e_OutboxInvoiceSGKExtensions { get; set; }
    }
}
