//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_OutboxInvoiceHeaderExportSaleExtensions
    {
        public System.Guid UUID { get; set; }
        public string IncotermCode { get; set; }
        public string PayeeFinancialAccountID { get; set; }
        public string PaymentMeansCode { get; set; }
        public string PaymentChannelCode { get; set; }
        public string GTBRefNumber { get; set; }
        public string GCBRegNumber { get; set; }
        public string ProfileID { get; set; }
        public decimal CarriageAmount { get; set; }
        public decimal InsuranceAmount { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual e_OutboxInvoiceHeader e_OutboxInvoiceHeader { get; set; }
    }
}
