//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseFilter
    {
        public string ExpenseCode { get; set; }
        public string UnitOfMeasureCode1 { get; set; }
        public bool UseInternet { get; set; }
        public bool UsePOS { get; set; }
        public bool UseStore { get; set; }
        public bool UseManufacturing { get; set; }
        public short SupplyPeriod { get; set; }
        public string ItemAccountGrCode { get; set; }
        public string ItemTaxGrCode { get; set; }
        public string ItemVendorGrCode { get; set; }
        public bool IsFixedExpense { get; set; }
        public decimal CompanyCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ExpenseAtt01 { get; set; }
        public string ExpenseAtt02 { get; set; }
        public string ExpenseAtt03 { get; set; }
        public string ExpenseAtt04 { get; set; }
        public string ExpenseAtt05 { get; set; }
    }
}
