//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrEmployeeMonthlySum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hrEmployeeMonthlySum()
        {
            this.hrSGKMonthlyDocument = new HashSet<hrSGKMonthlyDocument>();
        }
    
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public decimal CompanyCode { get; set; }
        public short ValidYear { get; set; }
        public byte ValidMonth { get; set; }
        public string WorkPlaceCode { get; set; }
        public decimal GrossIncome { get; set; }
        public decimal NetIncome { get; set; }
        public decimal DeductionAmount { get; set; }
        public byte PremiumDay { get; set; }
        public byte MissingWorkDay { get; set; }
        public string MissingWorkReasonCode { get; set; }
        public decimal SGKBase { get; set; }
        public decimal SGKBaseTransferred { get; set; }
        public decimal SGKBaseTransferorUsed { get; set; }
        public decimal UnemploymentEmployee { get; set; }
        public decimal UnemploymentEmployer { get; set; }
        public decimal UnemploymentEmployerAdd { get; set; }
        public decimal PensionEmployee { get; set; }
        public decimal PensionEmployer { get; set; }
        public decimal PensionEmployerAdd { get; set; }
        public decimal HealthEmployee { get; set; }
        public decimal HealthEmployer { get; set; }
        public decimal HealthEmployerAdd { get; set; }
        public decimal SGDPEmployee { get; set; }
        public decimal SGDPEmployer { get; set; }
        public decimal SGDPEmployerAdd { get; set; }
        public decimal ShortTermInsurance { get; set; }
        public decimal IncomeTaxRelief { get; set; }
        public decimal StampDutyRelief { get; set; }
        public decimal IncomeTaxBase { get; set; }
        public decimal IncomeTaxAmount { get; set; }
        public decimal StampDutyBase { get; set; }
        public decimal StampDutyReliefBase { get; set; }
        public decimal StampDutyAmount { get; set; }
        public float AGIRate { get; set; }
        public decimal AGIAmount { get; set; }
        public decimal ELDEmployee { get; set; }
        public decimal ELDEmployer { get; set; }
        public bool IsPostingJournal { get; set; }
        public System.DateTime JournalDate { get; set; }
        public bool IsUnchangeable { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public decimal RDReliefAmount { get; set; }
        public decimal IncomeTaxIncentiveAmount { get; set; }
        public decimal SGKBaseDuePay { get; set; }
        public decimal MinWageTaxReliefBase { get; set; }
        public decimal MinWageTaxReliefAmount { get; set; }
        public decimal MinWageStampDutyReliefBase { get; set; }
        public decimal MinWageStampDutyReliefAmount { get; set; }
    
        public virtual cdMissingWorkReason cdMissingWorkReason { get; set; }
        public virtual hrEmployeePayrollProfile hrEmployeePayrollProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hrSGKMonthlyDocument> hrSGKMonthlyDocument { get; set; }
    }
}
