//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public string Müşteri_Kodu { get; set; }
        public string Müşteri_Adı { get; set; }
        public string Ofis { get; set; }
        public string Ofis_Adı { get; set; }
        public byte Müşteri_Tipi { get; set; }
        public string Müşteri_Tipi_Açıklaması { get; set; }
        public string Satış_Kanalı { get; set; }
        public string Para_Birimi { get; set; }
        public System.DateTime Mutabakat_Tarihi { get; set; }
        public System.DateTime Hesap_Açılış_Tarihi { get; set; }
        public bool E_Faturaya_Tabidir { get; set; }
        public bool Ticari_E_Fatura { get; set; }
        public bool Gerçek_Kişilik__Şahıs_ { get; set; }
        public string TC_Kimlik_No { get; set; }
        public string Vergi_Numarası { get; set; }
        public string Vergi_Dairesi_Kodu { get; set; }
        public string Vergi_Dairesi_Açıklaması { get; set; }
        public string Mersis_Numarası { get; set; }
        public string Kampanya_Grubu { get; set; }
        public string Hesap_İskonto_Grubu { get; set; }
        public string Perakende_Satış_Fiyat_Grubu { get; set; }
        public string Toptan_Satış_Fiyat_Grubu { get; set; }
        public string Markup___Hakediş_Grubu { get; set; }
        public bool VIP_Müşteri { get; set; }
        public bool Kullanım_Dışı { get; set; }
        public decimal Şirket_Kodu { get; set; }
        public string CustomerAtt01 { get; set; }
        public string CustomerAtt02 { get; set; }
        public string CustomerAtt03 { get; set; }
        public string CustomerAtt04 { get; set; }
        public string CustomerAtt05 { get; set; }
        public string CustomerAtt06 { get; set; }
        public string CustomerAtt07 { get; set; }
        public string CustomerAtt08 { get; set; }
        public string CustomerAtt09 { get; set; }
        public string CustomerAtt10 { get; set; }
        public string CustomerAtt11 { get; set; }
        public string CustomerAtt12 { get; set; }
        public string CustomerAtt13 { get; set; }
        public string CustomerAtt14 { get; set; }
        public string CustomerAtt15 { get; set; }
    }
}
