//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesReceivableAttributes
    {
        public string ChequeCode { get; set; }
        public byte ChequeTypeCode { get; set; }
        public string BankCode { get; set; }
        public string BankBranchCode { get; set; }
        public string NotesReceivableAtt01 { get; set; }
        public string NotesReceivableAtt02 { get; set; }
        public string NotesReceivableAtt03 { get; set; }
        public string NotesReceivableAtt04 { get; set; }
        public string NotesReceivableAtt05 { get; set; }
    }
}
