//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prBankBranch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prBankBranch()
        {
            this.cdCheque = new HashSet<cdCheque>();
            this.cdCurrAcc = new HashSet<cdCurrAcc>();
            this.cdLetterOfGuarantee = new HashSet<cdLetterOfGuarantee>();
            this.prCurrAccBankAccNo = new HashSet<prCurrAccBankAccNo>();
            this.trBankPaymentInstructionLine = new HashSet<trBankPaymentInstructionLine>();
            this.trBankPaymentListLine = new HashSet<trBankPaymentListLine>();
        }
    
        public string BankCode { get; set; }
        public string BankBranchCode { get; set; }
        public string Description { get; set; }
        public string CountryCode { get; set; }
        public string StateCode { get; set; }
        public string CityCode { get; set; }
        public string DistrictCode { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual cdBank cdBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdCheque> cdCheque { get; set; }
        public virtual cdCity cdCity { get; set; }
        public virtual cdCountry cdCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdCurrAcc> cdCurrAcc { get; set; }
        public virtual cdDistrict cdDistrict { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdLetterOfGuarantee> cdLetterOfGuarantee { get; set; }
        public virtual cdState cdState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prCurrAccBankAccNo> prCurrAccBankAccNo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trBankPaymentInstructionLine> trBankPaymentInstructionLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trBankPaymentListLine> trBankPaymentListLine { get; set; }
    }
}
