//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prChannelTemplateCurrAcc
    {
        public decimal CompanyCode { get; set; }
        public string ChannelTemplateCode { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public System.Guid SubCurrAccID { get; set; }
        public int SortOrder { get; set; }
        public byte ChannelTypeCode { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual bsChannelType bsChannelType { get; set; }
        public virtual cdChannelTemplate cdChannelTemplate { get; set; }
    }
}
