//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prConfirmationRuleStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prConfirmationRuleStep()
        {
            this.prConfirmationRuleStepUser = new HashSet<prConfirmationRuleStepUser>();
        }
    
        public System.Guid ConfirmationRuleID { get; set; }
        public int SortOrder { get; set; }
        public bool IsRequired { get; set; }
        public int ExpireTimeForNextStep { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual cdConfirmationRule cdConfirmationRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prConfirmationRuleStepUser> prConfirmationRuleStepUser { get; set; }
    }
}
