//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prCompanyCreditCardEarnedPoints
    {
        public System.Guid CompanyCreditCardEarnedPointID { get; set; }
        public string CompanyCreditCardCode { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string Description { get; set; }
        public string RefNumber { get; set; }
        public decimal Point { get; set; }
        public bool IsPostingToJournal { get; set; }
        public Nullable<System.Guid> InvoiceHeaderID { get; set; }
        public Nullable<System.Guid> JournalHeaderID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual cdCompanyCreditCard cdCompanyCreditCard { get; set; }
        public virtual trInvoiceHeader trInvoiceHeader { get; set; }
        public virtual trJournalHeader trJournalHeader { get; set; }
    }
}
