//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prCustomerPresentCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prCustomerPresentCard()
        {
            this.prCurrAccDefault = new HashSet<prCurrAccDefault>();
        }
    
        public string CardNumber { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public string PresentCardTypeCode { get; set; }
        public string CustomerCRMGroupCode { get; set; }
        public bool IsCRMFormFilled { get; set; }
        public bool IsCRMActive { get; set; }
        public byte ActivationStatusCode { get; set; }
        public string PhoneNumber { get; set; }
        public string ConfirmationFormTypeCode { get; set; }
        public string FormNumber { get; set; }
        public string ConfirmationFormStatusCode { get; set; }
        public string InactivationReasonCode { get; set; }
        public bool IsCreditCard { get; set; }
        public System.DateTime LastValidDate { get; set; }
        public short CSV { get; set; }
        public string CreditCardTypeCode { get; set; }
        public System.DateTime IssueDate { get; set; }
        public decimal CompanyCode { get; set; }
        public string OfficeCode { get; set; }
        public string StoreCode { get; set; }
        public short PosTerminalID { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public Nullable<System.Guid> CurrAccPersonalDataConfirmationID { get; set; }
    
        public virtual bsPresentCardActivationStatus bsPresentCardActivationStatus { get; set; }
        public virtual cdConfirmationFormStatus cdConfirmationFormStatus { get; set; }
        public virtual cdConfirmationFormType cdConfirmationFormType { get; set; }
        public virtual cdCreditCardType cdCreditCardType { get; set; }
        public virtual cdCurrAcc cdCurrAcc { get; set; }
        public virtual cdCustomerCRMGroup cdCustomerCRMGroup { get; set; }
        public virtual cdInactivationReason cdInactivationReason { get; set; }
        public virtual cdPresentCardType cdPresentCardType { get; set; }
        public virtual prCurrAccContact prCurrAccContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prCurrAccDefault> prCurrAccDefault { get; set; }
    }
}
