//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prDeclarationGLAccs
    {
        public decimal CompanyCode { get; set; }
        public byte DeclarationTypeCode { get; set; }
        public byte TypeCode { get; set; }
        public string LineCode { get; set; }
        public byte DeclarationPostTypeCode { get; set; }
        public string GLAccCode { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual bsDeclarationPostType bsDeclarationPostType { get; set; }
        public virtual bsDeclarationType bsDeclarationType { get; set; }
        public virtual cdGLAcc cdGLAcc { get; set; }
    }
}
