//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prDiscountOfferPaymentProvider
    {
        public string ProcessCode { get; set; }
        public byte DiscountOfferStageCode { get; set; }
        public string DiscountOfferCode { get; set; }
        public string PaymentProviderCode { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual bsDiscountOfferStage bsDiscountOfferStage { get; set; }
        public virtual cdDiscountOffer cdDiscountOffer { get; set; }
        public virtual cdPaymentProvider cdPaymentProvider { get; set; }
    }
}
