//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prEmployeeLeaveRequestHour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prEmployeeLeaveRequestHour()
        {
            this.prEmployeeLeaveHour = new HashSet<prEmployeeLeaveHour>();
        }
    
        public System.Guid EmployeeLeaveRequestHourID { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.TimeSpan LeaveHour { get; set; }
        public string LeaveTypeCode { get; set; }
        public string RequestDescription { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string Address { get; set; }
        public string DepartmentManagerCode { get; set; }
        public string HRManagerCode { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> StatusUpdateDate { get; set; }
        public string StatusUpdateUserName { get; set; }
        public string RejectReason { get; set; }
        public System.Guid EmployeeLeaveRequestHeaderID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual cdCurrAcc cdCurrAcc { get; set; }
        public virtual cdLeaveType cdLeaveType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prEmployeeLeaveHour> prEmployeeLeaveHour { get; set; }
    }
}
