//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prGLAccOnlineBank
    {
        public decimal CompanyCode { get; set; }
        public string OnlineBankWebServiceCode { get; set; }
        public string GLAccCode { get; set; }
        public string CostCenterCode { get; set; }
        public string GLTypeCode { get; set; }
        public byte BankOpTypeCode { get; set; }
        public string ATAtt01 { get; set; }
        public string ATAtt02 { get; set; }
        public string ATAtt03 { get; set; }
        public string ATAtt04 { get; set; }
        public string ATAtt05 { get; set; }
        public string FTAtt01 { get; set; }
        public string FTAtt02 { get; set; }
        public string FTAtt03 { get; set; }
        public string FTAtt04 { get; set; }
        public string FTAtt05 { get; set; }
        public string GLAccOnlineBankAccountCode { get; set; }
        public string FirmID { get; set; }
        public string FirmCode { get; set; }
        public string FirmName { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public bool AutoCreateOnlineBankTrans { get; set; }
    
        public virtual cdBankOpType cdBankOpType { get; set; }
        public virtual cdCostCenter cdCostCenter { get; set; }
        public virtual cdGLAcc cdGLAcc { get; set; }
        public virtual cdGLType cdGLType { get; set; }
        public virtual cdOnlineBankWebService cdOnlineBankWebService { get; set; }
    }
}
