//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prItemVariant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prItemVariant()
        {
            this.cdBOM = new HashSet<cdBOM>();
            this.cdRoll = new HashSet<cdRoll>();
            this.e_InboxShipmentLineV3Items = new HashSet<e_InboxShipmentLineV3Items>();
            this.prBOMContent = new HashSet<prBOMContent>();
            this.prItemBarcode = new HashSet<prItemBarcode>();
            this.prItemBatchBarcode = new HashSet<prItemBatchBarcode>();
            this.prItemSerialNumberPool = new HashSet<prItemSerialNumberPool>();
            this.prItemStockLevel = new HashSet<prItemStockLevel>();
            this.prLinkedProductContent = new HashSet<prLinkedProductContent>();
            this.prMarketPlaceItemVariant = new HashSet<prMarketPlaceItemVariant>();
            this.tpPurchaseRequisitionClosedByInventory = new HashSet<tpPurchaseRequisitionClosedByInventory>();
            this.tpSupportResolveMaterial = new HashSet<tpSupportResolveMaterial>();
            this.trAllocationProduct = new HashSet<trAllocationProduct>();
            this.trContractProduct = new HashSet<trContractProduct>();
            this.trDepartmentReceiptLine = new HashSet<trDepartmentReceiptLine>();
            this.trInnerLine = new HashSet<trInnerLine>();
            this.trInnerLineInventoryTransfer = new HashSet<trInnerLineInventoryTransfer>();
            this.trInnerOrderLine = new HashSet<trInnerOrderLine>();
            this.trInvoiceLine = new HashSet<trInvoiceLine>();
            this.trItemTestLine = new HashSet<trItemTestLine>();
            this.trOrderAsnLine = new HashSet<trOrderAsnLine>();
            this.trOrderLine = new HashSet<trOrderLine>();
            this.trProposalLine = new HashSet<trProposalLine>();
            this.trReportedSaleLine = new HashSet<trReportedSaleLine>();
            this.trShipmentLine = new HashSet<trShipmentLine>();
            this.trStock = new HashSet<trStock>();
            this.trSupportRequestHeader = new HashSet<trSupportRequestHeader>();
            this.trTransferPlanProduct = new HashSet<trTransferPlanProduct>();
            this.trVehicleUnLoadingLine = new HashSet<trVehicleUnLoadingLine>();
        }
    
        public byte ItemTypeCode { get; set; }
        public string ItemCode { get; set; }
        public string ColorCode { get; set; }
        public string ItemDim1Code { get; set; }
        public string ItemDim2Code { get; set; }
        public string ItemDim3Code { get; set; }
        public long PLU { get; set; }
        public byte IsSalesOrderClosed { get; set; }
        public bool IsPurchaseOrderClosed { get; set; }
        public bool IsLocked { get; set; }
        public bool IsBlocked { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public bool UseInternet { get; set; }
        public bool IsStoreOrderClosed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdBOM> cdBOM { get; set; }
        public virtual cdColor cdColor { get; set; }
        public virtual cdItem cdItem { get; set; }
        public virtual cdItemDim1 cdItemDim1 { get; set; }
        public virtual cdItemDim2 cdItemDim2 { get; set; }
        public virtual cdItemDim3 cdItemDim3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdRoll> cdRoll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<e_InboxShipmentLineV3Items> e_InboxShipmentLineV3Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prBOMContent> prBOMContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prItemBarcode> prItemBarcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prItemBatchBarcode> prItemBatchBarcode { get; set; }
        public virtual prItemMeasuresOfVolume prItemMeasuresOfVolume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prItemSerialNumberPool> prItemSerialNumberPool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prItemStockLevel> prItemStockLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prLinkedProductContent> prLinkedProductContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prMarketPlaceItemVariant> prMarketPlaceItemVariant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpPurchaseRequisitionClosedByInventory> tpPurchaseRequisitionClosedByInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpSupportResolveMaterial> tpSupportResolveMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trAllocationProduct> trAllocationProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trContractProduct> trContractProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trDepartmentReceiptLine> trDepartmentReceiptLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trInnerLine> trInnerLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trInnerLineInventoryTransfer> trInnerLineInventoryTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trInnerOrderLine> trInnerOrderLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trInvoiceLine> trInvoiceLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trItemTestLine> trItemTestLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trOrderAsnLine> trOrderAsnLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trOrderLine> trOrderLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trProposalLine> trProposalLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trReportedSaleLine> trReportedSaleLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trShipmentLine> trShipmentLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trStock> trStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trSupportRequestHeader> trSupportRequestHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trTransferPlanProduct> trTransferPlanProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trVehicleUnLoadingLine> trVehicleUnLoadingLine { get; set; }
    }
}
