//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prMarketPlaceCategoryConvert
    {
        public System.Guid MarketPlaceCategoryConvertID { get; set; }
        public string MarketPlaceCode { get; set; }
        public string AttTypeCode01 { get; set; }
        public string AttCode01 { get; set; }
        public string AttTypeCode02 { get; set; }
        public string AttCode02 { get; set; }
        public string AttTypeCode03 { get; set; }
        public string AttCode03 { get; set; }
        public string AttTypeCode04 { get; set; }
        public string AttCode04 { get; set; }
        public string AttTypeCode05 { get; set; }
        public string AttCode05 { get; set; }
        public string MarketPlaceCategoryID { get; set; }
        public string MarketPlaceCategoryName { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual bsMarketPlace bsMarketPlace { get; set; }
    }
}
