//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prMarketPlaceProductHierarchyConvert
    {
        public string MarketPlaceCode { get; set; }
        public int NebimV3ProductHierarchyID { get; set; }
        public string MarketPlaceCategoryID { get; set; }
        public string MarketPlaceCategoryName { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual bsMarketPlace bsMarketPlace { get; set; }
        public virtual dfProductHierarchy dfProductHierarchy { get; set; }
    }
}
