//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prMT940ProcessRules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prMT940ProcessRules()
        {
            this.tpBankMT940 = new HashSet<tpBankMT940>();
        }
    
        public System.Guid MT940ProcessRulesID { get; set; }
        public decimal CompanyCode { get; set; }
        public string BankCode { get; set; }
        public string MT940ProcessCode { get; set; }
        public bool ForDebitProcess { get; set; }
        public string DescriptionRule { get; set; }
        public int Priority { get; set; }
        public byte BankTransTypeCode { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public string GLAccCode { get; set; }
        public string CostCenterCode { get; set; }
        public string GLTypeCode { get; set; }
        public byte BankOpTypeCode { get; set; }
        public byte DocumentTypeCode { get; set; }
        public string DocumentTypeDescription { get; set; }
        public string PaymentMethod { get; set; }
        public string LineDescription { get; set; }
        public string ATAtt01 { get; set; }
        public string ATAtt02 { get; set; }
        public string ATAtt03 { get; set; }
        public string ATAtt04 { get; set; }
        public string ATAtt05 { get; set; }
        public string FTAtt01 { get; set; }
        public string FTAtt02 { get; set; }
        public string FTAtt03 { get; set; }
        public string FTAtt04 { get; set; }
        public string FTAtt05 { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public byte BankCurrAccTypeCode { get; set; }
        public string BankCurrAccCode { get; set; }
    
        public virtual bsBankTransType bsBankTransType { get; set; }
        public virtual bsDocumentType bsDocumentType { get; set; }
        public virtual bsMT940Process bsMT940Process { get; set; }
        public virtual cdBank cdBank { get; set; }
        public virtual cdBankOpType cdBankOpType { get; set; }
        public virtual cdCompany cdCompany { get; set; }
        public virtual cdCostCenter cdCostCenter { get; set; }
        public virtual cdCurrAcc cdCurrAcc { get; set; }
        public virtual cdCurrAcc cdCurrAcc1 { get; set; }
        public virtual cdGLAcc cdGLAcc { get; set; }
        public virtual cdGLType cdGLType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpBankMT940> tpBankMT940 { get; set; }
    }
}
