//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductColorAttributes
    {
        public byte ItemTypeCode { get; set; }
        public string ItemCode { get; set; }
        public string ColorCode { get; set; }
        public string ProductColorAtt01 { get; set; }
        public string ProductColorAtt02 { get; set; }
        public string ProductColorAtt03 { get; set; }
        public string ProductColorAtt04 { get; set; }
        public string ProductColorAtt05 { get; set; }
        public string ProductColorAtt06 { get; set; }
        public string ProductColorAtt07 { get; set; }
        public string ProductColorAtt08 { get; set; }
        public string ProductColorAtt09 { get; set; }
        public string ProductColorAtt10 { get; set; }
        public string ProductColorAtt11 { get; set; }
        public string ProductColorAtt12 { get; set; }
        public string ProductColorAtt13 { get; set; }
        public string ProductColorAtt14 { get; set; }
        public string ProductColorAtt15 { get; set; }
    }
}
