//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prPresentCardActivationSteps
    {
        public string PresentCardTypeCode { get; set; }
        public byte ActivationProcessCode { get; set; }
        public string ConfirmationFormTypeCode { get; set; }
        public string ConditionTypeCode { get; set; }
        public string UserWarningCode { get; set; }
        public string NegotaryUserWarningCode { get; set; }
        public string Originator { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public string SMSGatewayServiceCode { get; set; }
    
        public virtual bsPresentCardActivationProcess bsPresentCardActivationProcess { get; set; }
        public virtual cdConditionType cdConditionType { get; set; }
        public virtual cdConfirmationFormType cdConfirmationFormType { get; set; }
        public virtual cdUserWarning cdUserWarning { get; set; }
        public virtual cdUserWarning cdUserWarning1 { get; set; }
    }
}
