//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prStoreStatus
    {
        public byte StoreTypeCode { get; set; }
        public string StoreCode { get; set; }
        public System.DateTime OperationDate { get; set; }
        public float SalesArea { get; set; }
        public float TotalArea { get; set; }
        public string RentCurrencyCode { get; set; }
        public decimal RentAmount { get; set; }
        public string Description { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
    
        public virtual cdCurrAcc cdCurrAcc { get; set; }
        public virtual cdCurrency cdCurrency { get; set; }
    }
}
