//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prStoreProperties
    {
        public byte StoreTypeCode { get; set; }
        public string StoreCode { get; set; }
        public int UrbanPopulation { get; set; }
        public short StoreCarCount { get; set; }
        public short VitrineCount { get; set; }
        public short MannequinCount { get; set; }
        public short EmployeeCount { get; set; }
        public byte CashDrawerCount { get; set; }
        public short FloorCount { get; set; }
        public short EntranceCount { get; set; }
        public System.DateTime LastRemodelDate { get; set; }
        public byte StorePriceLevelCode { get; set; }
        public byte StoreClimateZoneCode { get; set; }
        public byte StoreConceptCode { get; set; }
        public string StoreDistributionGroupCode { get; set; }
        public string StoreCRMGroupCode { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.Guid RowGuid { get; set; }
        public string StoreDisplayName { get; set; }
    
        public virtual cdCurrAcc cdCurrAcc { get; set; }
        public virtual cdStoreClimateZone cdStoreClimateZone { get; set; }
        public virtual cdStoreConcept cdStoreConcept { get; set; }
        public virtual cdStoreCRMGroup cdStoreCRMGroup { get; set; }
        public virtual cdStoreDistributionGroup cdStoreDistributionGroup { get; set; }
        public virtual cdStorePriceLevel cdStorePriceLevel { get; set; }
    }
}
