//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportQueries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportQueries()
        {
            this.ReportParameters = new HashSet<ReportParameters>();
        }
    
        public int Id { get; set; }
        public string QueryName { get; set; }
        public string QueryText { get; set; }
        public string DefaultReportPath { get; set; }
        public bool IsBlocked { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportParameters> ReportParameters { get; set; }
    }
}
