//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailSalesNoOrderR
    {
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public Nullable<System.TimeSpan> OperationTime { get; set; }
        public string DocumentNumber { get; set; }
        public string SeriesNumber { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public int ProcessFlowCode { get; set; }
        public byte ItemTypeCode { get; set; }
        public string ItemCode { get; set; }
        public string ColorCode { get; set; }
        public string ItemDim1Code { get; set; }
        public string ItemDim2Code { get; set; }
        public string ItemDim3Code { get; set; }
        public Nullable<bool> IsInvoiced { get; set; }
        public string Invoice { get; set; }
        public decimal CompanyCode { get; set; }
        public string OfficeCode { get; set; }
        public string StoreCode { get; set; }
        public string WareHouseCode { get; set; }
        public short PosTerminalID { get; set; }
        public decimal PolicyCompanyCode { get; set; }
        public string PolicyOfficeCode { get; set; }
        public Nullable<double> Qty1 { get; set; }
        public Nullable<decimal> PriceVI { get; set; }
        public Nullable<double> AmountVI { get; set; }
        public Nullable<double> DiscountVI { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> TaxBase { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public byte TaxTypeCode { get; set; }
        public string SalespersonCode { get; set; }
        public string PaymentPlanCode { get; set; }
        public string RoundsmanCode { get; set; }
        public string ReturnReasonCode { get; set; }
        public byte DiscountReasonCode { get; set; }
        public string ProcessCode { get; set; }
        public int FormType { get; set; }
        public int SortOrder { get; set; }
        public System.Guid LineID { get; set; }
        public System.Guid HeaderID { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string ATAtt01 { get; set; }
    }
}
