//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailCustomerFilter
    {
        public string RetailCustomerCode { get; set; }
        public string TitleCode { get; set; }
        public string FirstLastName { get; set; }
        public string OfficeCode { get; set; }
        public string OfficeCountryCode { get; set; }
        public byte GenderCode { get; set; }
        public bool IsMarried { get; set; }
        public bool IsVIP { get; set; }
        public string PromotionGroupCode { get; set; }
        public string CustomerDiscountGrCode { get; set; }
        public string RetailSalePriceGroupCode { get; set; }
        public decimal CompanyCode { get; set; }
        public System.DateTime AccountOpeningDate { get; set; }
        public string IdentityNum { get; set; }
        public string RetailCustomerAtt01 { get; set; }
        public string RetailCustomerAtt02 { get; set; }
        public string RetailCustomerAtt03 { get; set; }
        public string RetailCustomerAtt04 { get; set; }
        public string RetailCustomerAtt05 { get; set; }
        public string RetailCustomerAtt06 { get; set; }
        public string RetailCustomerAtt07 { get; set; }
        public string RetailCustomerAtt08 { get; set; }
        public string RetailCustomerAtt09 { get; set; }
        public string RetailCustomerAtt10 { get; set; }
        public string RetailCustomerAtt11 { get; set; }
        public string RetailCustomerAtt12 { get; set; }
        public string RetailCustomerAtt13 { get; set; }
        public string RetailCustomerAtt14 { get; set; }
        public string RetailCustomerAtt15 { get; set; }
    }
}
