//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpAirConnUSB_GetInfo
    {
        public System.Guid TransactionID { get; set; }
        public string cashbox_factory_number { get; set; }
        public string cashbox_tax_number { get; set; }
        public string cashregister_factory_number { get; set; }
        public string cashregister_model { get; set; }
        public string company_name { get; set; }
        public string company_tax_number { get; set; }
        public string firmware_version { get; set; }
        public int last_doc_number { get; set; }
        public System.DateTime last_online_time { get; set; }
        public System.DateTime not_after { get; set; }
        public System.DateTime not_before { get; set; }
        public string object_address { get; set; }
        public string object_name { get; set; }
        public string object_tax_number { get; set; }
        public System.DateTime oldest_document_time { get; set; }
        public string qr_code_url { get; set; }
        public string state { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
