//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpEArchiveIntegratorControl
    {
        public System.Guid EArchiveIntegratorControlID { get; set; }
        public Nullable<System.Guid> InvoiceHeaderID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.TimeSpan InvoiceTime { get; set; }
        public decimal CompanyCode { get; set; }
        public string EInvoiceNumber { get; set; }
        public decimal TaxBase { get; set; }
        public decimal Vat { get; set; }
        public decimal NetAmount { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
