//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpMobildevIVTEmailReconciliation
    {
        public System.Guid MobildevIVTEmailReconciliationID { get; set; }
        public int LogId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Msisdn { get; set; }
        public bool HasIVTForm { get; set; }
        public int StatusId { get; set; }
        public string StatusText { get; set; }
        public int TypeId { get; set; }
        public string TypeText { get; set; }
        public string Note { get; set; }
        public string Reasons { get; set; }
        public int PermSourceId { get; set; }
        public string PermSourceText { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
