//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpMobildevIVTContactReconciliation
    {
        public string Email { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Reason { get; set; }
        public string Note { get; set; }
        public string StatusId { get; set; }
        public string StatusText { get; set; }
        public string PermSourceId { get; set; }
        public string PermSourceText { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public System.DateTime updatedAt { get; set; }
    }
}
