//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpMobildevIVTReconciliation
    {
        public System.Guid MobildevIVTReconciliationID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Msisdn { get; set; }
        public string Email { get; set; }
        public int EtkMsisdn { get; set; }
        public int EtkCall { get; set; }
        public int EtkEmail { get; set; }
        public int EtkShare { get; set; }
        public int KvkkShare { get; set; }
        public int KvkkProcess { get; set; }
        public int KvkkInternational { get; set; }
        public int ExtendedLoyalty { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int AccountTypeId { get; set; }
        public string AccountTypeText { get; set; }
        public int PermSourceId { get; set; }
        public string PermSourceText { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
