//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpSettings
    {
        public System.Guid RowID { get; set; }
        public bool UseInventory { get; set; }
        public bool AutoInventoryTransfer { get; set; }
        public int AutoInventoryTransferTimerTick { get; set; }
        public string DefaultWarehouseCode { get; set; }
        public bool IsSendMailForEInvoice { get; set; }
        public bool IsSendSMSForEInvoice { get; set; }
        public int AutoAssignmentTimerTick { get; set; }
        public bool UseOrderManagement { get; set; }
        public bool UseShipmentManagement { get; set; }
    }
}
