//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAttributesFilter
    {
        public byte ItemTypeCode { get; set; }
        public string ItemCode { get; set; }
        public string ServiceAtt01 { get; set; }
        public string ServiceAtt02 { get; set; }
        public string ServiceAtt03 { get; set; }
        public string ServiceAtt04 { get; set; }
        public string ServiceAtt05 { get; set; }
        public string ServiceAtt06 { get; set; }
        public string ServiceAtt07 { get; set; }
        public string ServiceAtt08 { get; set; }
        public string ServiceAtt09 { get; set; }
        public string ServiceAtt10 { get; set; }
        public string ServiceAtt11 { get; set; }
        public string ServiceAtt12 { get; set; }
        public string ServiceAtt13 { get; set; }
        public string ServiceAtt14 { get; set; }
        public string ServiceAtt15 { get; set; }
        public string ServiceAtt16 { get; set; }
        public string ServiceAtt17 { get; set; }
        public string ServiceAtt18 { get; set; }
        public string ServiceAtt19 { get; set; }
        public string ServiceAtt20 { get; set; }
    }
}
