//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SevkEmirleri
    {
        public System.Guid DispOrderHeaderID { get; set; }
        public byte Sevk_Emri_Tipi { get; set; }
        public string Süreç_Kodu { get; set; }
        public string Süreç_Açıklaması { get; set; }
        public string Sevk_Emri_Numarası { get; set; }
        public bool İade { get; set; }
        public System.DateTime Sevk_Emri_Tarihi { get; set; }
        public System.TimeSpan Sevk_Emri_Zamanı { get; set; }
        public System.DateTime İrsaliye_Tarihi { get; set; }
        public System.TimeSpan Sevkiyat_Saati { get; set; }
        public string Teslimatçı_Kodu { get; set; }
        public string Açıklama { get; set; }
        public string Dahili_Açıklama { get; set; }
        public byte Cari_Hesap_Tipi { get; set; }
        public string Cari_Hesap_Tipi_Açıklaması { get; set; }
        public string Cari_Hesap_Kodu { get; set; }
        public string Cari_Hesap_Açıklaması { get; set; }
        public Nullable<System.Guid> SubCurrAccID { get; set; }
        public string Alt_Hesap_Adı { get; set; }
        public string Alt_Hesap_Kodu { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public decimal Şirket_Kodu { get; set; }
        public string Ofis { get; set; }
        public byte Mağaza_Cari_Tipi { get; set; }
        public string Mağaza_Kodu { get; set; }
        public string Depo_Kodu { get; set; }
        public string Karşı_Depo_Kodu { get; set; }
        public bool Tamamlandı { get; set; }
        public bool Formdan_Dökümü_Yazdırıldı { get; set; }
        public bool Değişikliklere_Kilitlenmiş { get; set; }
        public string Uygulama_Kodu { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public string Oluşturan_Kullanıcı { get; set; }
        public System.DateTime Oluşturulma_Tarihi { get; set; }
        public string Son_Güncelleyen_Kullanıcı { get; set; }
        public System.DateTime Son_Güncelleme_Tarihi { get; set; }
        public string Müşteri_Mal_Kabul_Numarası { get; set; }
        public bool Onaylandı { get; set; }
        public string ConfirmedUser { get; set; }
        public System.DateTime Onaylanan_Tarih { get; set; }
        public System.Guid DispOrderLineID { get; set; }
        public int Sırası { get; set; }
        public double Miktar { get; set; }
        public double Miktar__2_ { get; set; }
        public double Giren_Miktar { get; set; }
        public string Satır_Açıklaması { get; set; }
        public string Barkod { get; set; }
        public System.Guid Satır_Sıra_ID { get; set; }
        public Nullable<System.Guid> ReserveLineID { get; set; }
        public Nullable<System.DateTime> Sipariş_Teslim_Tarihi { get; set; }
        public byte Madde_Tipi { get; set; }
        public string Madde_Kodu { get; set; }
        public string Madde_Açıklaması { get; set; }
        public string Renk_Kodu { get; set; }
        public string Renk_Açıklaması { get; set; }
        public string ItemDim1Code { get; set; }
        public string ItemDim2Code { get; set; }
        public string ItemDim3Code { get; set; }
        public double Sipariş_Miktarı { get; set; }
        public double Sipariş_Miktarı__2_ { get; set; }
        public string Sipariş_Ref__Numarası { get; set; }
        public System.DateTime Sipariş_Tarihi { get; set; }
        public System.DateTime Teslim_Tarihi { get; set; }
        public System.DateTime Planlanan_Yükleme_Tarihi { get; set; }
        public string İthalat_Dosya_Numarası { get; set; }
        public string İhracat_Dosya_Numarası { get; set; }
        public string DefBarkod { get; set; }
        public Nullable<double> KDV_Hariç_Tutar { get; set; }
        public Nullable<double> KDV_Dahil_Tutar { get; set; }
    }
}
