//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreWarehouses
    {
        public string CustomerCode { get; set; }
        public Nullable<System.Guid> SubCurrAccID { get; set; }
        public string CustomerWarehouseCode { get; set; }
        public string StoreCode { get; set; }
        public string StoreWarehouseCode { get; set; }
    }
}
