//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stProductRemainingInOrder
    {
        public long ProductRemainingInOrderID { get; set; }
        public decimal CompanyCode { get; set; }
        public string OfficeCode { get; set; }
        public string SalesChannelCode { get; set; }
        public string StoreCode { get; set; }
        public string ProductCode { get; set; }
        public string ColorCode { get; set; }
        public string ItemDim1Code { get; set; }
        public string ItemDim2Code { get; set; }
        public string ItemDim3Code { get; set; }
        public double RemainingInOrderQty1 { get; set; }
    }
}
