//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpCanceledUTSDeclaration
    {
        public System.Guid CanceledUTSDeclarationID { get; set; }
        public string ApplicationCode { get; set; }
        public System.Guid ApplicationID { get; set; }
        public System.Guid ApplicationLineID { get; set; }
        public System.Guid StockID { get; set; }
        public string InnerProcessCode { get; set; }
        public string ProcessCode { get; set; }
        public bool IsReturn { get; set; }
        public byte TransTypeCode { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string DocumentNumber { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public Nullable<System.Guid> SubCurrAccID { get; set; }
        public decimal CompanyCode { get; set; }
        public string OfficeCode { get; set; }
        public byte StoreTypeCode { get; set; }
        public string StoreCode { get; set; }
        public string WarehouseCode { get; set; }
        public string FromOfficeCode { get; set; }
        public string FromStoreCode { get; set; }
        public string FromWarehouseCode { get; set; }
        public string DataMatrixCode { get; set; }
        public byte ItemTypeCode { get; set; }
        public string ItemCode { get; set; }
        public string ColorCode { get; set; }
        public string ItemDim1Code { get; set; }
        public string ItemDim2Code { get; set; }
        public string ItemDim3Code { get; set; }
        public string Barcode { get; set; }
        public string SerialNumber { get; set; }
        public string ManufactureDate { get; set; }
        public string PartyCode { get; set; }
        public double Qty1 { get; set; }
        public double Qty2 { get; set; }
        public string CancelledUserName { get; set; }
        public System.DateTime CancelledDate { get; set; }
        public bool IsDeclaredToUTS { get; set; }
    }
}
