//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpInvoiceLineAgentPerformance
    {
        public System.Guid InvoiceLineAgentPerformanceID { get; set; }
        public System.Guid InvoiceLineID { get; set; }
        public System.Guid AgentReservationHeaderID { get; set; }
        public System.Guid AgentContractHeaderID { get; set; }
        public decimal AgentAmount { get; set; }
        public decimal AgentOfficeAmount { get; set; }
        public decimal TourGuideAmount { get; set; }
        public decimal TourDriverAmount { get; set; }
        public decimal TourLeaderAmount { get; set; }
        public decimal TourHelperGuideAmount { get; set; }
        public decimal HotelAmount { get; set; }
        public decimal HotelPersonnelAmount { get; set; }
        public decimal SpecialAmount { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual trAgentContractHeader trAgentContractHeader { get; set; }
        public virtual trAgentReservationHeader trAgentReservationHeader { get; set; }
        public virtual trInvoiceLine trInvoiceLine { get; set; }
    }
}
