//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpOrderDiscountOffer
    {
        public System.Guid OrderDiscountOfferID { get; set; }
        public System.Guid OrderHeaderID { get; set; }
        public Nullable<System.Guid> OrderLineID { get; set; }
        public bool IsEarned { get; set; }
        public string DiscountOfferCode { get; set; }
        public decimal DiscountAmount { get; set; }
        public double DiscountRate { get; set; }
        public byte PaymentTypeCode { get; set; }
        public string DiscountVoucherTypeCode { get; set; }
        public string SerialNumber { get; set; }
        public decimal EarnedAmount { get; set; }
        public decimal UsedAmount { get; set; }
        public string DiscountPointTypeCode { get; set; }
        public Nullable<System.Guid> CustomerDiscountPointID { get; set; }
        public decimal EarnedPoint { get; set; }
        public decimal UsedPoint { get; set; }
        public bool IsBooster { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string Password { get; set; }
        public bool UsedAsPayment { get; set; }
        public Nullable<System.Guid> OrderCancelDetailHeaderID { get; set; }
    
        public virtual trOrderHeader trOrderHeader { get; set; }
        public virtual trOrderLine trOrderLine { get; set; }
    }
}
