//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpProposalDiscountOfferContributor
    {
        public System.Guid ProposalDiscountOfferContributorID { get; set; }
        public System.Guid ProposalHeaderID { get; set; }
        public Nullable<System.Guid> ProposalLineID { get; set; }
        public string DiscountOfferCode { get; set; }
        public decimal Amount { get; set; }
        public decimal DiscountAmount { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual trProposalHeader trProposalHeader { get; set; }
        public virtual trProposalLine trProposalLine { get; set; }
    }
}
