//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trAdjustCostInventoryLine
    {
        public System.Guid AdjustCostHeaderID { get; set; }
        public System.Guid CostOfGoodsSoldHeaderID { get; set; }
        public System.Guid EndOfPeriodInventoryID { get; set; }
        public decimal IncreaseAmount { get; set; }
        public decimal ReduceAmount { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual trAdjustCostInventory trAdjustCostInventory { get; set; }
        public virtual trEndOfPeriodInventory trEndOfPeriodInventory { get; set; }
    }
}
