//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trBadDebtTransLineInstalment
    {
        public System.Guid BadDebtTransLineInstalmentID { get; set; }
        public string CurrencyCode { get; set; }
        public decimal Debit { get; set; }
        public decimal PaidDebit { get; set; }
        public decimal LateChargeAmount { get; set; }
        public decimal PaidLateChargeAmount { get; set; }
        public double LateChargeRate { get; set; }
        public decimal Expense { get; set; }
        public decimal PaidExpense { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.Guid> DebitLineID { get; set; }
        public Nullable<System.Guid> OrderPaymentPlanID { get; set; }
        public System.Guid BadDebtTransLineID { get; set; }
        public bool DoNotAccrueExpenseAmount { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual cdCurrency cdCurrency { get; set; }
        public virtual trBadDebtTransLine trBadDebtTransLine { get; set; }
        public virtual trDebitLine trDebitLine { get; set; }
        public virtual trOrderPaymentPlan trOrderPaymentPlan { get; set; }
    }
}
