//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trBankCreditLineCurrency
    {
        public System.Guid BankCreditLineID { get; set; }
        public string CurrencyCode { get; set; }
        public double ExchangeRate { get; set; }
        public string RelationCurrencyCode { get; set; }
        public decimal CapitalAmount { get; set; }
        public decimal InterestAmount { get; set; }
        public decimal KKDFAmount { get; set; }
        public decimal BSMVAmount { get; set; }
        public decimal DeductionAmount1 { get; set; }
        public decimal DeductionAmount2 { get; set; }
        public decimal DeductionAmount3 { get; set; }
        public decimal Amount { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual cdCurrency cdCurrency { get; set; }
        public virtual cdCurrency cdCurrency1 { get; set; }
        public virtual trBankCreditLine trBankCreditLine { get; set; }
    }
}
