//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trBankCreditLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trBankCreditLine()
        {
            this.trBankCreditLineCurrency = new HashSet<trBankCreditLineCurrency>();
            this.trBankLine = new HashSet<trBankLine>();
        }
    
        public System.Guid BankCreditLineID { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime DueDate { get; set; }
        public decimal CompanyCode { get; set; }
        public string GLAccCode { get; set; }
        public string ExpenseGLAccCode { get; set; }
        public string ReflectionGLAccCode { get; set; }
        public string LineDescription { get; set; }
        public string CostCenterCode { get; set; }
        public string GLTypeCode { get; set; }
        public string DocCurrencyCode { get; set; }
        public bool IsPostingJournal { get; set; }
        public System.DateTime JournalDate { get; set; }
        public System.Guid BankCreditHeaderID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual cdCostCenter cdCostCenter { get; set; }
        public virtual cdCurrency cdCurrency { get; set; }
        public virtual cdGLAcc cdGLAcc { get; set; }
        public virtual cdGLAcc cdGLAcc1 { get; set; }
        public virtual cdGLAcc cdGLAcc2 { get; set; }
        public virtual cdGLType cdGLType { get; set; }
        public virtual trBankCreditHeader trBankCreditHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trBankCreditLineCurrency> trBankCreditLineCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trBankLine> trBankLine { get; set; }
    }
}
