//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trContract()
        {
            this.tpContractATAttribute = new HashSet<tpContractATAttribute>();
            this.tpContractITAttribute = new HashSet<tpContractITAttribute>();
            this.trContractProduct = new HashSet<trContractProduct>();
        }
    
        public System.Guid ContractID { get; set; }
        public byte ContractTypeCode { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public System.TimeSpan DocumentTime { get; set; }
        public string Description { get; set; }
        public string ContractContentCode { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public Nullable<System.Guid> SubCurrAccID { get; set; }
        public Nullable<System.Guid> ContactID { get; set; }
        public decimal CompanyCode { get; set; }
        public string OfficeCode { get; set; }
        public byte StoreTypeCode { get; set; }
        public string StoreCode { get; set; }
        public string GLTypeCode { get; set; }
        public string DocCurrencyCode { get; set; }
        public string LocalCurrencyCode { get; set; }
        public double ExchangeRate { get; set; }
        public decimal MonthlyFee { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public byte InvoicePeriod { get; set; }
        public byte LastInvoicedMonth { get; set; }
        public string PaymentPlanCode { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsLocked { get; set; }
        public bool IsPrinted { get; set; }
        public System.DateTime ClosedDate { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<bool> Canceled { get; set; }
        public System.DateTime CancelDate { get; set; }
        public string CancelReason { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual bsApplication bsApplication { get; set; }
        public virtual bsContractType bsContractType { get; set; }
        public virtual cdCompany cdCompany { get; set; }
        public virtual cdContractContent cdContractContent { get; set; }
        public virtual cdCurrAcc cdCurrAcc { get; set; }
        public virtual cdCurrAcc cdCurrAcc1 { get; set; }
        public virtual cdCurrency cdCurrency { get; set; }
        public virtual cdCurrency cdCurrency1 { get; set; }
        public virtual cdGLType cdGLType { get; set; }
        public virtual cdOffice cdOffice { get; set; }
        public virtual cdPaymentPlan cdPaymentPlan { get; set; }
        public virtual prCurrAccContact prCurrAccContact { get; set; }
        public virtual prSubCurrAcc prSubCurrAcc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpContractATAttribute> tpContractATAttribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpContractITAttribute> tpContractITAttribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trContractProduct> trContractProduct { get; set; }
    }
}
