//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trEmployeeDebit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trEmployeeDebit()
        {
            this.trEmployeeDebitCurrency = new HashSet<trEmployeeDebitCurrency>();
            this.trPaymentLine = new HashSet<trPaymentLine>();
        }
    
        public System.Guid EmployeeDebitID { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public decimal CompanyCode { get; set; }
        public string DeductionCode { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string DocumentNumber { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Description { get; set; }
        public string LocalCurrencyCode { get; set; }
        public string DocCurrencyCode { get; set; }
        public bool IsLocked { get; set; }
        public bool IsPostingJournal { get; set; }
        public System.DateTime JournalDate { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual bsApplication bsApplication { get; set; }
        public virtual cdCurrency cdCurrency { get; set; }
        public virtual cdCurrency cdCurrency1 { get; set; }
        public virtual cdDeduction cdDeduction { get; set; }
        public virtual hrEmployeePayrollProfile hrEmployeePayrollProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trEmployeeDebitCurrency> trEmployeeDebitCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trPaymentLine> trPaymentLine { get; set; }
    }
}
