//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trFixedAssetBookHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trFixedAssetBookHeader()
        {
            this.trFixedAssetBookLine = new HashSet<trFixedAssetBookLine>();
        }
    
        public System.Guid FixedAssetBookHeaderID { get; set; }
        public decimal CompanyCode { get; set; }
        public byte ItemTypeCode { get; set; }
        public string ItemCode { get; set; }
        public short ValidYear { get; set; }
        public byte DepreciationMethodCode { get; set; }
        public bool IsVUK { get; set; }
        public string LocCurrencyCode { get; set; }
        public decimal BookValueAtBeginningOfPeriod { get; set; }
        public float DepreciationRate { get; set; }
        public float ReassessmentRate { get; set; }
        public decimal DepreciationExpense { get; set; }
        public decimal ReassessmentExpense { get; set; }
        public decimal ReassessmentAmount { get; set; }
        public decimal SalesAmount { get; set; }
        public decimal PeriodDepreciation { get; set; }
        public decimal AccumulatedDepreciation { get; set; }
        public decimal BookValueAtEndOfPeriod { get; set; }
        public decimal PeriodBookValue { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual cdCurrency cdCurrency { get; set; }
        public virtual cdItem cdItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trFixedAssetBookLine> trFixedAssetBookLine { get; set; }
    }
}
