//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trInnerLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trInnerLine()
        {
            this.stItemRollNumber = new HashSet<stItemRollNumber>();
            this.stItemSerialNumber = new HashSet<stItemSerialNumber>();
            this.tpInnerITAttribute = new HashSet<tpInnerITAttribute>();
            this.tpInnerLineDocument = new HashSet<tpInnerLineDocument>();
            this.tpInnerLinePurchaseInvoiceLine = new HashSet<tpInnerLinePurchaseInvoiceLine>();
            this.trAdjustCostInnerLine = new HashSet<trAdjustCostInnerLine>();
            this.trInnerLineBOM = new HashSet<trInnerLineBOM>();
            this.trInnerLineCostCenterRates = new HashSet<trInnerLineCostCenterRates>();
            this.trInnerLineGiftCard = new HashSet<trInnerLineGiftCard>();
            this.trItemTestLine = new HashSet<trItemTestLine>();
            this.trTaxIncurredLine = new HashSet<trTaxIncurredLine>();
        }
    
        public System.Guid InnerLineID { get; set; }
        public int SortOrder { get; set; }
        public byte ItemTypeCode { get; set; }
        public string ItemCode { get; set; }
        public string ColorCode { get; set; }
        public string ItemDim1Code { get; set; }
        public string ItemDim2Code { get; set; }
        public string ItemDim3Code { get; set; }
        public double Qty1 { get; set; }
        public double Qty2 { get; set; }
        public string LineDescription { get; set; }
        public string UsedBarcode { get; set; }
        public string SerialNumber { get; set; }
        public string BatchCode { get; set; }
        public string CurrencyCode { get; set; }
        public decimal CostPrice { get; set; }
        public decimal CostAmount { get; set; }
        public string ScrapReasonCode { get; set; }
        public string CostCenterCode { get; set; }
        public string GLTypeCode { get; set; }
        public Nullable<System.Guid> SupportRequestHeaderID { get; set; }
        public System.Guid InnerHeaderID { get; set; }
        public int InnerLineSumID { get; set; }
        public int InnerLineSerialSumID { get; set; }
        public Nullable<System.Guid> InnerOrderLineID { get; set; }
        public Nullable<int> InnerLineBOMID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string SectionCode { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual cdBatch cdBatch { get; set; }
        public virtual cdCostCenter cdCostCenter { get; set; }
        public virtual cdCurrency cdCurrency { get; set; }
        public virtual cdGLType cdGLType { get; set; }
        public virtual cdScrapReason cdScrapReason { get; set; }
        public virtual prItemVariant prItemVariant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stItemRollNumber> stItemRollNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stItemSerialNumber> stItemSerialNumber { get; set; }
        public virtual tpInnerCustomsTransferImportInvoiceLine tpInnerCustomsTransferImportInvoiceLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpInnerITAttribute> tpInnerITAttribute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpInnerLineDocument> tpInnerLineDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpInnerLinePurchaseInvoiceLine> tpInnerLinePurchaseInvoiceLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trAdjustCostInnerLine> trAdjustCostInnerLine { get; set; }
        public virtual trInnerHeader trInnerHeader { get; set; }
        public virtual trInnerOrderLine trInnerOrderLine { get; set; }
        public virtual trSupportRequestHeader trSupportRequestHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trInnerLineBOM> trInnerLineBOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trInnerLineCostCenterRates> trInnerLineCostCenterRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trInnerLineGiftCard> trInnerLineGiftCard { get; set; }
        public virtual trInnerLineInventoryTransfer trInnerLineInventoryTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trItemTestLine> trItemTestLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trTaxIncurredLine> trTaxIncurredLine { get; set; }
    }
}
