//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trPayrollLineTally
    {
        public System.Guid PayrollLineID { get; set; }
        public string EarningsCode { get; set; }
        public byte WorkDay { get; set; }
        public double WorkHour { get; set; }
        public byte WeekendDay { get; set; }
        public double WeekendHour { get; set; }
        public byte OfficialOffDay { get; set; }
        public double officialOffHour { get; set; }
        public byte ReligiousHoliday { get; set; }
        public double ReligiousHolidayHour { get; set; }
        public byte SabbaticalDay { get; set; }
        public double SabbaticalHour { get; set; }
        public double MissingHours { get; set; }
        public double OvertimeHour { get; set; }
        public double Rate { get; set; }
        public double EarningsDay { get; set; }
        public string EarningsCurrencyCode { get; set; }
        public double ExchangeRate { get; set; }
        public decimal Amount { get; set; }
        public bool IsGrossEarnings { get; set; }
        public decimal EarningsWorkDay { get; set; }
        public decimal EarningsWeekendDay { get; set; }
        public decimal EarningsOfficialOffDay { get; set; }
        public decimal EarningsReligiousHoliday { get; set; }
        public decimal EarningsSabbaticalDay { get; set; }
        public decimal EarningsOther { get; set; }
        public decimal IncomeTaxRelief { get; set; }
        public decimal IncomeTaxBase { get; set; }
        public decimal IncomeTaxAmount { get; set; }
        public decimal StampDutyBase { get; set; }
        public decimal StampDutyAmount { get; set; }
        public decimal SGKRelief { get; set; }
        public decimal SGKBase { get; set; }
        public decimal UnemploymentEmployee { get; set; }
        public decimal PensionEmployee { get; set; }
        public decimal HealthEmployee { get; set; }
        public decimal SGDPEmployee { get; set; }
        public decimal UnemploymentEmployer { get; set; }
        public decimal PensionEmployer { get; set; }
        public decimal HealthEmployer { get; set; }
        public decimal SGDPEmployer { get; set; }
        public decimal ShortTermInsurance { get; set; }
        public decimal WageGarnishment { get; set; }
        public decimal AGIAmount { get; set; }
        public decimal NetAmount { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public double RDHours { get; set; }
        public decimal RDReliefAmount { get; set; }
        public decimal StampDutyRelief { get; set; }
        public decimal StampDutyReliefBase { get; set; }
        public decimal MinWageTaxReliefBase { get; set; }
        public decimal MinWageTaxReliefAmount { get; set; }
        public decimal MinWageStampDutyReliefBase { get; set; }
        public decimal MinWageStampDutyReliefAmount { get; set; }
        public decimal Amount2 { get; set; }
        public decimal Amount3 { get; set; }
    
        public virtual cdCurrency cdCurrency { get; set; }
        public virtual cdEarnings cdEarnings { get; set; }
        public virtual trPayrollLine trPayrollLine { get; set; }
    }
}
