//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trSalesPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trSalesPlan()
        {
            this.trSalesPlanChannel = new HashSet<trSalesPlanChannel>();
            this.trSalesPlanProduct = new HashSet<trSalesPlanProduct>();
            this.trSalesPlanProductQty = new HashSet<trSalesPlanProductQty>();
        }
    
        public System.Guid SalesPlanID { get; set; }
        public string SalesPlanNumber { get; set; }
        public System.DateTime PlanDate { get; set; }
        public decimal CompanyCode { get; set; }
        public short SalesYear { get; set; }
        public byte SalesMonth { get; set; }
        public byte SalesIsoWeek { get; set; }
        public string SalesPlanTypeCode { get; set; }
        public byte SalesWeek { get; set; }
        public string Description { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsLocked { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsConfirmed { get; set; }
        public string ConfirmedUserName { get; set; }
        public System.DateTime ConfirmedDate { get; set; }
        public bool IsPostingOrder { get; set; }
        public bool IsPostingSaleOrder { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual bsApplication bsApplication { get; set; }
        public virtual cdCompany cdCompany { get; set; }
        public virtual cdSalesPlanType cdSalesPlanType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trSalesPlanChannel> trSalesPlanChannel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trSalesPlanProduct> trSalesPlanProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trSalesPlanProductQty> trSalesPlanProductQty { get; set; }
    }
}
