//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trTransferPlanData_DefT2
    {
        public System.Guid TransferPlanID { get; set; }
        public System.Guid TransferPlanProductID { get; set; }
        public System.Guid TransferPlanChannelID { get; set; }
        public int SortOrder { get; set; }
        public double AvailableInventoryQty1 { get; set; }
        public double TransferNotApprovedQty1 { get; set; }
        public double TargetChannelInventoryQty1 { get; set; }
        public double Donem_Satis { get; set; }
        public System.DateTime LastIncomingDate { get; set; }
        public double Merkez_Depo_Envanteri { get; set; }
        public string InventoryLimitCode { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string Sizes { get; set; }
    }
}
