//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trVendorPriceListHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trVendorPriceListHeader()
        {
            this.trVendorPriceListLine = new HashSet<trVendorPriceListLine>();
        }
    
        public System.Guid VendorPriceListHeaderID { get; set; }
        public string VendorPriceListNumber { get; set; }
        public System.DateTime VendorPriceListDate { get; set; }
        public System.TimeSpan VendorPriceListTime { get; set; }
        public decimal CompanyCode { get; set; }
        public byte VendorTypeCode { get; set; }
        public string VendorCode { get; set; }
        public System.DateTime ValidDate { get; set; }
        public string DocCurrencyCode { get; set; }
        public string Description { get; set; }
        public bool IsTaxIncluded { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsLocked { get; set; }
        public bool IsConfirmed { get; set; }
        public string ConfirmedUserName { get; set; }
        public System.DateTime ConfirmedDate { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<System.Guid> ApplicationID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual bsApplication bsApplication { get; set; }
        public virtual cdCompany cdCompany { get; set; }
        public virtual cdCurrAcc cdCurrAcc { get; set; }
        public virtual cdCurrency cdCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trVendorPriceListLine> trVendorPriceListLine { get; set; }
    }
}
