//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trVirementLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trVirementLine()
        {
            this.tpVirementFTAttribute = new HashSet<tpVirementFTAttribute>();
        }
    
        public System.Guid VirementLineID { get; set; }
        public int SortOrder { get; set; }
        public string DebitReasonCode { get; set; }
        public string LineDescription { get; set; }
        public string GLTypeCode { get; set; }
        public System.Guid CreditDebitHeaderID { get; set; }
        public System.Guid DebitDebitHeaderID { get; set; }
        public System.Guid VirementHeaderID { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual cdDebitReason cdDebitReason { get; set; }
        public virtual cdGLType cdGLType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpVirementFTAttribute> tpVirementFTAttribute { get; set; }
        public virtual trDebitHeader trDebitHeader { get; set; }
        public virtual trDebitHeader trDebitHeader1 { get; set; }
        public virtual trVirementHeader trVirementHeader { get; set; }
    }
}
