//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public string Ürün_Kodu { get; set; }
        public string Ürün_Adı { get; set; }
        public byte Varyant_Tipi { get; set; }
        public byte Ürün_Tipi { get; set; }
        public string Ürün_Tipi_Açıklması { get; set; }
        public string Birim_Cinsi_1 { get; set; }
        public string Birim_Cinsi_2 { get; set; }
        public float Çevrim_Oranı { get; set; }
        public string Madde_Vergi_Grubu { get; set; }
        public string Ödeme_Planı_Grubu { get; set; }
        public string İskonto_Grubu { get; set; }
        public string Kampanya_Grubu { get; set; }
        public string Kampanya_Grubu_2 { get; set; }
        public string Muhasebe_Hesap_Grubu { get; set; }
        public string Tedarikçi_Grubu { get; set; }
        public short Tedarik_Süresi { get; set; }
        public short Garanti_Periyodu { get; set; }
        public int Sipariş_Teslim_Süresi { get; set; }
        public short Raf_Ömrü { get; set; }
        public byte Fiyat_Seviyesi { get; set; }
        public byte Moda_Algısı { get; set; }
        public byte Ticari_Rolü { get; set; }
        public string Mağaza_Kapasite_Grubu { get; set; }
        public bool Mağazada_Satışa_Açık { get; set; }
        public bool İnternette_Satışa_Açık { get; set; }
        public bool Seri_Numarası_Takibi_Var { get; set; }
        public bool Üretimde_Kullanılacak { get; set; }
        public bool Kullanım_Dışı { get; set; }
        public int Kolleksiyon_Grubu { get; set; }
        public string Ürün_Sezonu { get; set; }
        public string Ürün_Kolleksiyonu { get; set; }
        public string Öykü_Panosu { get; set; }
        public int Ürün_Hiyerarşisindeki_Yeri { get; set; }
        public string ProductHierarchyLevel01 { get; set; }
        public string ProductHierarchyLevel02 { get; set; }
        public string ProductHierarchyLevel03 { get; set; }
        public string ProductHierarchyLevel04 { get; set; }
        public string ProductHierarchyLevel05 { get; set; }
        public string ProductHierarchyLevel06 { get; set; }
        public string ProductHierarchyLevel07 { get; set; }
        public string ProductHierarchyLevel08 { get; set; }
        public string ProductHierarchyLevel09 { get; set; }
        public string ProductHierarchyLevel10 { get; set; }
        public string ProductAtt01 { get; set; }
        public string ProductAtt02 { get; set; }
        public string ProductAtt03 { get; set; }
        public string ProductAtt04 { get; set; }
        public string ProductAtt05 { get; set; }
        public string ProductAtt06 { get; set; }
        public string ProductAtt07 { get; set; }
        public string ProductAtt08 { get; set; }
        public string ProductAtt09 { get; set; }
        public string ProductAtt10 { get; set; }
        public string ProductAtt11 { get; set; }
        public string ProductAtt12 { get; set; }
        public string ProductAtt13 { get; set; }
        public string ProductAtt14 { get; set; }
        public string ProductAtt15 { get; set; }
        public string ProductAtt16 { get; set; }
        public string ProductAtt17 { get; set; }
        public string ProductAtt18 { get; set; }
        public string ProductAtt19 { get; set; }
        public string ProductAtt20 { get; set; }
    }
}
