//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RPlusAndroid_FindWarehouseTransferApproving
    {
        public string InnerNumber { get; set; }
        public System.DateTime OperationDate { get; set; }
        public string InnerProcessCode { get; set; }
        public decimal CompanyCode { get; set; }
        public string OfficeCode { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseDescription { get; set; }
        public string ShipWarehouseCode { get; set; }
        public string ShipWarehouseDescription { get; set; }
        public string Series { get; set; }
        public string SeriesNumber { get; set; }
        public System.Guid InnerHeaderID { get; set; }
    }
}
