//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RGN_GetOrderListFromSalesChannel
    {
        public string MarketPlace { get; set; }
        public string ErpOrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string EcommerceOrderNo { get; set; }
        public string MarketPlaceOrderNo { get; set; }
        public string InvoiceNameSurname { get; set; }
        public string InvoiceAddress { get; set; }
        public string ShippingNameSurname { get; set; }
        public string ShippingAddress { get; set; }
        public string CustomerEmail { get; set; }
        public string CargoCompany { get; set; }
        public string CargoNumber { get; set; }
        public string CargoTrackingUrl { get; set; }
        public string MarketPlaceStatus { get; set; }
        public string DYSStatus { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ColorName { get; set; }
        public string Size { get; set; }
        public double Qty { get; set; }
        public decimal Amount { get; set; }
        public string ShelfCollectionNo { get; set; }
        public System.DateTime ShelfDate { get; set; }
        public string CollectionUser { get; set; }
        public bool CollectionComplete { get; set; }
        public string PackageNo { get; set; }
        public string ShelfSectionNo { get; set; }
        public System.DateTime InoiceDate { get; set; }
        public string InvoiceRefNo { get; set; }
        public System.DateTime FilterOrderDate { get; set; }
    }
}
