//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RGN_PWB_SaleInvoiceList
    {
        public string ProcessCode { get; set; }
        public byte CurrAccTypeCode { get; set; }
        public string CurrAccCode { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string EInvoiceNumber { get; set; }
        public bool IsReturn { get; set; }
        public string StoreCode { get; set; }
        public string WarehouseCode { get; set; }
        public byte ItemTypeCode { get; set; }
        public string ItemCode { get; set; }
        public string ColorCode { get; set; }
        public string ItemDim1Code { get; set; }
        public string ItemDim2Code { get; set; }
        public double SalesQty { get; set; }
        public Nullable<decimal> Loc_Price { get; set; }
        public Nullable<decimal> Loc_PriceVI { get; set; }
        public Nullable<decimal> Loc_Amount { get; set; }
        public Nullable<decimal> Loc_AmountVI { get; set; }
        public Nullable<decimal> Loc_LTotalDiscount { get; set; }
        public Nullable<decimal> Loc_LTotalDiscountVI { get; set; }
        public Nullable<decimal> Loc_TTotalDiscount { get; set; }
        public Nullable<decimal> Loc_TTotalDiscountVI { get; set; }
        public Nullable<decimal> Loc_TaxBase { get; set; }
        public Nullable<decimal> Loc_Vat { get; set; }
        public Nullable<decimal> Loc_NetAmount { get; set; }
        public Nullable<decimal> Doc_Price { get; set; }
        public Nullable<decimal> Doc_PriceVI { get; set; }
        public Nullable<decimal> Doc_Amount { get; set; }
        public Nullable<decimal> Doc_AmountVI { get; set; }
        public Nullable<decimal> Doc_LTotalDiscount { get; set; }
        public Nullable<decimal> Doc_LTotalDiscountVI { get; set; }
        public Nullable<decimal> Doc_TTotalDiscount { get; set; }
        public Nullable<decimal> Doc_TTotalDiscountVI { get; set; }
        public Nullable<decimal> Doc_TaxBase { get; set; }
        public Nullable<decimal> Doc_Vat { get; set; }
        public Nullable<decimal> Doc_NetAmount { get; set; }
    }
}
