//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RPlus_OrderPrintView
    {
        public System.Guid OrderHeaderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderNumber { get; set; }
        public string CurrAccCode { get; set; }
        public string CurrAccDescription { get; set; }
        public string Address { get; set; }
        public System.Guid OrderLineID { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public string ColorCode { get; set; }
        public string ItemDim1Code { get; set; }
        public double Qty1 { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal TaxBase { get; set; }
        public decimal Vat { get; set; }
        public decimal NetAmount { get; set; }
    }
}
