//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RPlus_ITAttribute
    {
        public byte AttributeTypeCode { get; set; }
        public string AttributeCode { get; set; }
        public string AttributeDescription { get; set; }
    }
}
