//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RGN_OrderRefNumberList
    {
        public string ProcessCode { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerDescription { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string Status { get; set; }
        public double TotalQty { get; set; }
        public double CancelQty1 { get; set; }
        public double ClosedQty1 { get; set; }
        public string DocumentNumber { get; set; }
        public string DocCurrencyCode { get; set; }
        public string WarehouseCode { get; set; }
    }
}
