//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_WarehouseLocationName
    {
        public string WarehouseCode { get; set; }
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<bool> OrderPickingShelf { get; set; }
        public int LocationID { get; set; }
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
    }
}
