//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zpBulutTahsilatCreditCardVPOSPaymentList
    {
        public System.Guid CorrelationID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string JsonData { get; set; }
        public bool PaymentIntegrated { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public long TransactionID { get; set; }
    }
}
