//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zpDmsRegisterPaidCheck
    {
        public System.Guid RegisterPaidCheckID { get; set; }
        public string MerchantID { get; set; }
        public string StationID { get; set; }
        public int RecognitionID { get; set; }
        public string DMSNo { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal PaidTotal { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string ResponseCode { get; set; }
        public int OperationStatus { get; set; }
        public int DmsTransactionID { get; set; }
        public decimal RewardPoints { get; set; }
        public string ApplicationName { get; set; }
        public string LocalCustomerNo { get; set; }
        public decimal FinancialPaidTotal { get; set; }
        public decimal NonFinancialPaidTotal { get; set; }
        public bool IsRetry { get; set; }
        public decimal OriginalTotalPrice { get; set; }
        public int RetryCount { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
