//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zpVodafoneAcService
    {
        public System.Guid OperationID { get; set; }
        public System.Guid TransactionID { get; set; }
        public string ServiceMethod { get; set; }
        public string FirmTransactionID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Msisdn { get; set; }
        public string CampaignPassword { get; set; }
        public decimal SaleAmount { get; set; }
        public string StoreReferance { get; set; }
        public int ResultCode { get; set; }
        public string ResultDescription { get; set; }
        public int CampaignID { get; set; }
        public int OperationStatus { get; set; }
        public int RetryCount { get; set; }
        public string ApplicationName { get; set; }
        public string CreatedUserName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedUserName { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
