//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zt_BNS_OrderDatamatrixList
    {
        public int RowNumber { get; set; }
        public string Brand { get; set; }
        public string Season_EN { get; set; }
        public string Customer { get; set; }
        public string Barcode { get; set; }
        public string Gender { get; set; }
        public string Category_EN { get; set; }
        public string Product { get; set; }
        public string ProductSeasonAndGroup { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Color_EN { get; set; }
        public string ProductGroup_EN { get; set; }
        public string CountryCode { get; set; }
        public string Vendor { get; set; }
        public string VendorAddress { get; set; }
        public string Currency { get; set; }
        public decimal NetPrice { get; set; }
        public decimal GrossPrice { get; set; }
        public decimal RetailPrice { get; set; }
        public string Material { get; set; }
        public string LINING { get; set; }
        public string Sole { get; set; }
        public string Size { get; set; }
        public string ColorCode { get; set; }
        public string ProductGroup_RU { get; set; }
        public string Material_RU { get; set; }
        public string Country_RU { get; set; }
        public string OrderNumber { get; set; }
        public string OrderHeaderID { get; set; }
        public string OrderLineID { get; set; }
        public double Qty1 { get; set; }
        public string Column_1 { get; set; }
        public string Column_2 { get; set; }
        public string Column_3 { get; set; }
        public string DataMatrixCode { get; set; }
        public string Column_5 { get; set; }
        public bool IsCompleted { get; set; }
    }
}
